
SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_familia_indigena_fam AS STRING) AS cod_familia_indigena_fam,
    CAST(cod_povo_indigena_fam AS STRING) AS cod_povo_indigena_fam,
    CAST(nom_povo_indigena_fam AS STRING) AS nom_povo_indigena_fam,
    CAST(vazio2 AS STRING) AS vazio2,
    CAST(cod_indigena_reside_fam AS STRING) AS cod_indigena_reside_fam,
    CAST(cod_reserva_indigena_fam AS STRING) AS cod_reserva_indigena_fam,
    CAST(nom_reserva_indigena_fam AS STRING) AS nom_reserva_indigena_fam,
    CAST(ind_reserva_indigena_fam AS STRING) AS ind_reserva_indigena_fam,
    CAST(ind_familia_quilombola_fam AS STRING) AS ind_familia_quilombola_fam,
    CAST(cod_comunidade_quilombola_fam AS STRING) AS cod_comunidade_quilombola_fam,
    CAST(nom_comunidade_quilombola_fam AS STRING) AS nom_comunidade_quilombola_fam,
    CAST(ind_comunidade_quilombola_fam AS STRING) AS ind_comunidade_quilombola_fam,
    CAST(qtd_pessoas_domic_fam AS STRING) AS qtd_pessoas_domic_fam,
    CAST(qtd_familias_domic_fam AS STRING) AS qtd_familias_domic_fam,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS STRING) AS qtd_pessoa_inter_0_17_anos_fam,
    CAST(ind_pessoa_inter_0_17_anos_fam AS STRING) AS ind_pessoa_inter_0_17_anos_fam,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS STRING) AS qtd_pessoa_inter_18_59_anos_fam,
    CAST(ind_pessoa_inter_18_59_anos_fam AS STRING) AS ind_pessoa_inter_18_59_anos_fam,
    CAST(qtd_pessoa_inter_60_anos_fam AS STRING) AS qtd_pessoa_inter_60_anos_fam,
    CAST(ind_pessoa_inter_60_anos_fam AS STRING) AS ind_pessoa_inter_60_anos_fam,
    CAST(val_desp_energia_fam AS STRING) AS val_desp_energia_fam,
    CAST(ind_desp_energia_fam AS STRING) AS ind_desp_energia_fam,
    CAST(val_desp_agua_esgoto_fam AS STRING) AS val_desp_agua_esgoto_fam,
    CAST(ind_desp_agua_esgoto_fam AS STRING) AS ind_desp_agua_esgoto_fam,
    CAST(val_desp_gas_fam AS STRING) AS val_desp_gas_fam,
    CAST(ind_desp_gas_fam AS STRING) AS ind_desp_gas_fam,
    CAST(val_desp_alimentacao_fam AS STRING) AS val_desp_alimentacao_fam,
    CAST(ind_desp_alimentacao_fam AS STRING) AS ind_desp_alimentacao_fam,
    CAST(val_desp_transpor_fam AS STRING) AS val_desp_transpor_fam,
    CAST(ind_desp_transpor_fam AS STRING) AS ind_desp_transpor_fam,
    CAST(val_desp_aluguel_fam AS STRING) AS val_desp_aluguel_fam,
    CAST(ind_desp_aluguel_fam AS STRING) AS ind_desp_aluguel_fam,
    CAST(val_desp_medicamentos_fam AS STRING) AS val_desp_medicamentos_fam,
    CAST(ind_desp_medicamentos_fam AS STRING) AS ind_desp_medicamentos_fam,
    CAST(nom_estab_assist_saude_fam AS STRING) AS nom_estab_assist_saude_fam,
    CAST(nu_estbo_saude AS STRING) AS nu_estbo_saude,
    CAST(nom_centro_assist_fam AS STRING) AS nom_centro_assist_fam,
    CAST(cod_centro_assist_fam AS STRING) AS cod_centro_assist_fam,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.03_0601`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_familia_indigena_fam AS STRING) AS cod_familia_indigena_fam,
    CAST(cod_povo_indigena_fam AS STRING) AS cod_povo_indigena_fam,
    CAST(nom_povo_indigena_fam AS STRING) AS nom_povo_indigena_fam,
    CAST(vazio2 AS STRING) AS vazio2,
    CAST(cod_indigena_reside_fam AS STRING) AS cod_indigena_reside_fam,
    CAST(cod_reserva_indigena_fam AS STRING) AS cod_reserva_indigena_fam,
    CAST(nom_reserva_indigena_fam AS STRING) AS nom_reserva_indigena_fam,
    CAST(ind_reserva_indigena_fam AS STRING) AS ind_reserva_indigena_fam,
    CAST(ind_familia_quilombola_fam AS STRING) AS ind_familia_quilombola_fam,
    CAST(cod_comunidade_quilombola_fam AS STRING) AS cod_comunidade_quilombola_fam,
    CAST(nom_comunidade_quilombola_fam AS STRING) AS nom_comunidade_quilombola_fam,
    CAST(ind_comunidade_quilombola_fam AS STRING) AS ind_comunidade_quilombola_fam,
    CAST(qtd_pessoas_domic_fam AS STRING) AS qtd_pessoas_domic_fam,
    CAST(qtd_familias_domic_fam AS STRING) AS qtd_familias_domic_fam,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS STRING) AS qtd_pessoa_inter_0_17_anos_fam,
    CAST(ind_pessoa_inter_0_17_anos_fam AS STRING) AS ind_pessoa_inter_0_17_anos_fam,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS STRING) AS qtd_pessoa_inter_18_59_anos_fam,
    CAST(ind_pessoa_inter_18_59_anos_fam AS STRING) AS ind_pessoa_inter_18_59_anos_fam,
    CAST(qtd_pessoa_inter_60_anos_fam AS STRING) AS qtd_pessoa_inter_60_anos_fam,
    CAST(ind_pessoa_inter_60_anos_fam AS STRING) AS ind_pessoa_inter_60_anos_fam,
    CAST(val_desp_energia_fam AS STRING) AS val_desp_energia_fam,
    CAST(ind_desp_energia_fam AS STRING) AS ind_desp_energia_fam,
    CAST(val_desp_agua_esgoto_fam AS STRING) AS val_desp_agua_esgoto_fam,
    CAST(ind_desp_agua_esgoto_fam AS STRING) AS ind_desp_agua_esgoto_fam,
    CAST(val_desp_gas_fam AS STRING) AS val_desp_gas_fam,
    CAST(ind_desp_gas_fam AS STRING) AS ind_desp_gas_fam,
    CAST(val_desp_alimentacao_fam AS STRING) AS val_desp_alimentacao_fam,
    CAST(ind_desp_alimentacao_fam AS STRING) AS ind_desp_alimentacao_fam,
    CAST(val_desp_transpor_fam AS STRING) AS val_desp_transpor_fam,
    CAST(ind_desp_transpor_fam AS STRING) AS ind_desp_transpor_fam,
    CAST(val_desp_aluguel_fam AS STRING) AS val_desp_aluguel_fam,
    CAST(ind_desp_aluguel_fam AS STRING) AS ind_desp_aluguel_fam,
    CAST(val_desp_medicamentos_fam AS STRING) AS val_desp_medicamentos_fam,
    CAST(ind_desp_medicamentos_fam AS STRING) AS ind_desp_medicamentos_fam,
    CAST(nom_estab_assist_saude_fam AS STRING) AS nom_estab_assist_saude_fam,
    CAST(nu_estbo_saude AS STRING) AS nu_estbo_saude,
    CAST(nom_centro_assist_fam AS STRING) AS nom_centro_assist_fam,
    CAST(cod_centro_assist_fam AS STRING) AS cod_centro_assist_fam,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.03_0603`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_familia_indigena_fam AS STRING) AS cod_familia_indigena_fam,
    CAST(cod_povo_indigena_fam AS STRING) AS cod_povo_indigena_fam,
    CAST(nom_povo_indigena_fam AS STRING) AS nom_povo_indigena_fam,
    CAST(vazio2 AS STRING) AS vazio2,
    CAST(cod_indigena_reside_fam AS STRING) AS cod_indigena_reside_fam,
    CAST(cod_reserva_indigena_fam AS STRING) AS cod_reserva_indigena_fam,
    CAST(nom_reserva_indigena_fam AS STRING) AS nom_reserva_indigena_fam,
    CAST(ind_reserva_indigena_fam AS STRING) AS ind_reserva_indigena_fam,
    CAST(ind_familia_quilombola_fam AS STRING) AS ind_familia_quilombola_fam,
    CAST(cod_comunidade_quilombola_fam AS STRING) AS cod_comunidade_quilombola_fam,
    CAST(nom_comunidade_quilombola_fam AS STRING) AS nom_comunidade_quilombola_fam,
    CAST(ind_comunidade_quilombola_fam AS STRING) AS ind_comunidade_quilombola_fam,
    CAST(qtd_pessoas_domic_fam AS STRING) AS qtd_pessoas_domic_fam,
    CAST(qtd_familias_domic_fam AS STRING) AS qtd_familias_domic_fam,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS STRING) AS qtd_pessoa_inter_0_17_anos_fam,
    CAST(ind_pessoa_inter_0_17_anos_fam AS STRING) AS ind_pessoa_inter_0_17_anos_fam,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS STRING) AS qtd_pessoa_inter_18_59_anos_fam,
    CAST(ind_pessoa_inter_18_59_anos_fam AS STRING) AS ind_pessoa_inter_18_59_anos_fam,
    CAST(qtd_pessoa_inter_60_anos_fam AS STRING) AS qtd_pessoa_inter_60_anos_fam,
    CAST(ind_pessoa_inter_60_anos_fam AS STRING) AS ind_pessoa_inter_60_anos_fam,
    CAST(val_desp_energia_fam AS STRING) AS val_desp_energia_fam,
    CAST(ind_desp_energia_fam AS STRING) AS ind_desp_energia_fam,
    CAST(val_desp_agua_esgoto_fam AS STRING) AS val_desp_agua_esgoto_fam,
    CAST(ind_desp_agua_esgoto_fam AS STRING) AS ind_desp_agua_esgoto_fam,
    CAST(val_desp_gas_fam AS STRING) AS val_desp_gas_fam,
    CAST(ind_desp_gas_fam AS STRING) AS ind_desp_gas_fam,
    CAST(val_desp_alimentacao_fam AS STRING) AS val_desp_alimentacao_fam,
    CAST(ind_desp_alimentacao_fam AS STRING) AS ind_desp_alimentacao_fam,
    CAST(val_desp_transpor_fam AS STRING) AS val_desp_transpor_fam,
    CAST(ind_desp_transpor_fam AS STRING) AS ind_desp_transpor_fam,
    CAST(val_desp_aluguel_fam AS STRING) AS val_desp_aluguel_fam,
    CAST(ind_desp_aluguel_fam AS STRING) AS ind_desp_aluguel_fam,
    CAST(val_desp_medicamentos_fam AS STRING) AS val_desp_medicamentos_fam,
    CAST(ind_desp_medicamentos_fam AS STRING) AS ind_desp_medicamentos_fam,
    CAST(nom_estab_assist_saude_fam AS STRING) AS nom_estab_assist_saude_fam,
    CAST(nu_estbo_saude AS STRING) AS nu_estbo_saude,
    CAST(nom_centro_assist_fam AS STRING) AS nom_centro_assist_fam,
    CAST(cod_centro_assist_fam AS STRING) AS cod_centro_assist_fam,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.03_0604`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_familia_indigena_fam AS STRING) AS cod_familia_indigena_fam,
    CAST(cod_povo_indigena_fam AS STRING) AS cod_povo_indigena_fam,
    CAST(nom_povo_indigena_fam AS STRING) AS nom_povo_indigena_fam,
    CAST(vazio2 AS STRING) AS vazio2,
    CAST(cod_indigena_reside_fam AS STRING) AS cod_indigena_reside_fam,
    CAST(cod_reserva_indigena_fam AS STRING) AS cod_reserva_indigena_fam,
    CAST(nom_reserva_indigena_fam AS STRING) AS nom_reserva_indigena_fam,
    CAST(ind_reserva_indigena_fam AS STRING) AS ind_reserva_indigena_fam,
    CAST(ind_familia_quilombola_fam AS STRING) AS ind_familia_quilombola_fam,
    CAST(cod_comunidade_quilombola_fam AS STRING) AS cod_comunidade_quilombola_fam,
    CAST(nom_comunidade_quilombola_fam AS STRING) AS nom_comunidade_quilombola_fam,
    CAST(ind_comunidade_quilombola_fam AS STRING) AS ind_comunidade_quilombola_fam,
    CAST(qtd_pessoas_domic_fam AS STRING) AS qtd_pessoas_domic_fam,
    CAST(qtd_familias_domic_fam AS STRING) AS qtd_familias_domic_fam,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS STRING) AS qtd_pessoa_inter_0_17_anos_fam,
    CAST(ind_pessoa_inter_0_17_anos_fam AS STRING) AS ind_pessoa_inter_0_17_anos_fam,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS STRING) AS qtd_pessoa_inter_18_59_anos_fam,
    CAST(ind_pessoa_inter_18_59_anos_fam AS STRING) AS ind_pessoa_inter_18_59_anos_fam,
    CAST(qtd_pessoa_inter_60_anos_fam AS STRING) AS qtd_pessoa_inter_60_anos_fam,
    CAST(ind_pessoa_inter_60_anos_fam AS STRING) AS ind_pessoa_inter_60_anos_fam,
    CAST(val_desp_energia_fam AS STRING) AS val_desp_energia_fam,
    CAST(ind_desp_energia_fam AS STRING) AS ind_desp_energia_fam,
    CAST(val_desp_agua_esgoto_fam AS STRING) AS val_desp_agua_esgoto_fam,
    CAST(ind_desp_agua_esgoto_fam AS STRING) AS ind_desp_agua_esgoto_fam,
    CAST(val_desp_gas_fam AS STRING) AS val_desp_gas_fam,
    CAST(ind_desp_gas_fam AS STRING) AS ind_desp_gas_fam,
    CAST(val_desp_alimentacao_fam AS STRING) AS val_desp_alimentacao_fam,
    CAST(ind_desp_alimentacao_fam AS STRING) AS ind_desp_alimentacao_fam,
    CAST(val_desp_transpor_fam AS STRING) AS val_desp_transpor_fam,
    CAST(ind_desp_transpor_fam AS STRING) AS ind_desp_transpor_fam,
    CAST(val_desp_aluguel_fam AS STRING) AS val_desp_aluguel_fam,
    CAST(ind_desp_aluguel_fam AS STRING) AS ind_desp_aluguel_fam,
    CAST(val_desp_medicamentos_fam AS STRING) AS val_desp_medicamentos_fam,
    CAST(ind_desp_medicamentos_fam AS STRING) AS ind_desp_medicamentos_fam,
    CAST(nom_estab_assist_saude_fam AS STRING) AS nom_estab_assist_saude_fam,
    CAST(nu_estbo_saude AS STRING) AS nu_estbo_saude,
    CAST(nom_centro_assist_fam AS STRING) AS nom_centro_assist_fam,
    CAST(cod_centro_assist_fam AS STRING) AS cod_centro_assist_fam,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.03_0609`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_familia_indigena_fam AS STRING) AS cod_familia_indigena_fam,
    CAST(cod_povo_indigena_fam AS STRING) AS cod_povo_indigena_fam,
    CAST(nom_povo_indigena_fam AS STRING) AS nom_povo_indigena_fam,
    CAST(vazio2 AS STRING) AS vazio2,
    CAST(cod_indigena_reside_fam AS STRING) AS cod_indigena_reside_fam,
    CAST(cod_reserva_indigena_fam AS STRING) AS cod_reserva_indigena_fam,
    CAST(nom_reserva_indigena_fam AS STRING) AS nom_reserva_indigena_fam,
    CAST(ind_reserva_indigena_fam AS STRING) AS ind_reserva_indigena_fam,
    CAST(ind_familia_quilombola_fam AS STRING) AS ind_familia_quilombola_fam,
    CAST(cod_comunidade_quilombola_fam AS STRING) AS cod_comunidade_quilombola_fam,
    CAST(nom_comunidade_quilombola_fam AS STRING) AS nom_comunidade_quilombola_fam,
    CAST(ind_comunidade_quilombola_fam AS STRING) AS ind_comunidade_quilombola_fam,
    CAST(qtd_pessoas_domic_fam AS STRING) AS qtd_pessoas_domic_fam,
    CAST(qtd_familias_domic_fam AS STRING) AS qtd_familias_domic_fam,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS STRING) AS qtd_pessoa_inter_0_17_anos_fam,
    CAST(ind_pessoa_inter_0_17_anos_fam AS STRING) AS ind_pessoa_inter_0_17_anos_fam,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS STRING) AS qtd_pessoa_inter_18_59_anos_fam,
    CAST(ind_pessoa_inter_18_59_anos_fam AS STRING) AS ind_pessoa_inter_18_59_anos_fam,
    CAST(qtd_pessoa_inter_60_anos_fam AS STRING) AS qtd_pessoa_inter_60_anos_fam,
    CAST(ind_pessoa_inter_60_anos_fam AS STRING) AS ind_pessoa_inter_60_anos_fam,
    CAST(val_desp_energia_fam AS STRING) AS val_desp_energia_fam,
    CAST(ind_desp_energia_fam AS STRING) AS ind_desp_energia_fam,
    CAST(val_desp_agua_esgoto_fam AS STRING) AS val_desp_agua_esgoto_fam,
    CAST(ind_desp_agua_esgoto_fam AS STRING) AS ind_desp_agua_esgoto_fam,
    CAST(val_desp_gas_fam AS STRING) AS val_desp_gas_fam,
    CAST(ind_desp_gas_fam AS STRING) AS ind_desp_gas_fam,
    CAST(val_desp_alimentacao_fam AS STRING) AS val_desp_alimentacao_fam,
    CAST(ind_desp_alimentacao_fam AS STRING) AS ind_desp_alimentacao_fam,
    CAST(val_desp_transpor_fam AS STRING) AS val_desp_transpor_fam,
    CAST(ind_desp_transpor_fam AS STRING) AS ind_desp_transpor_fam,
    CAST(val_desp_aluguel_fam AS STRING) AS val_desp_aluguel_fam,
    CAST(ind_desp_aluguel_fam AS STRING) AS ind_desp_aluguel_fam,
    CAST(val_desp_medicamentos_fam AS STRING) AS val_desp_medicamentos_fam,
    CAST(ind_desp_medicamentos_fam AS STRING) AS ind_desp_medicamentos_fam,
    CAST(nom_estab_assist_saude_fam AS STRING) AS nom_estab_assist_saude_fam,
    CAST(nu_estbo_saude AS STRING) AS nu_estbo_saude,
    CAST(nom_centro_assist_fam AS STRING) AS nom_centro_assist_fam,
    CAST(cod_centro_assist_fam AS STRING) AS cod_centro_assist_fam,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.03_0612`

