
SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_certidao_civil_pessoa AS string) AS id_certidao_civil,
    CAST(nom_cartorio_pessoa AS string) AS cartorio_certidao,
    CAST(cod_livro_termo_certid_pessoa AS string) AS livro_certidao_obito_excluido,
    CAST(cod_folha_termo_certid_pessoa AS string) AS folha_certidao,
    CAST(vazio_2 AS string) AS vazio,
    CAST(dta_emissao_certid_pessoa AS date) AS data_emissao_certidao,
    CAST(sig_uf_certid_pessoa AS string) AS sigla_uf_certidao,
    CAST(nom_munic_certid_pessoa AS string) AS municipio_certidao,
    CAST(cod_ibge_munic_certid_pessoa AS string) AS id_municipio_certidao,
    CAST(cod_cartorio_certid_pessoa AS string) AS id_cartorio_certidao,
    CAST(num_cpf_pessoa AS string) AS cpf,
    CAST(vazio_3 AS string) AS vazio,
    CAST(cod_complemento_pessoa AS string) AS id_complemento_rg,
    CAST(dta_emissao_ident_pessoa AS date) AS data_emissao_rg,
    CAST(sig_uf_ident_pessoa AS string) AS sigla_uf_rg,
    CAST(sig_orgao_emissor_pessoa AS string) AS orgao_emissor_rg,
    CAST(num_cart_trab_prev_soc_pessoa AS string) AS id_carteira_trabalho,
    CAST(num_serie_trab_prev_soc_pessoa AS string) AS id_serie_carteira_trabalho,
    CAST(dta_emissao_cart_trab_pessoa AS date) AS data_emissao_carteira_trabalho,
    CAST(sig_uf_cart_trab_pessoa AS string) AS sigla_uf_carteira_trabalho,
    CAST(num_titulo_eleitor_pessoa AS string) AS id_titulo_eleitor,
    CAST(num_zona_tit_eleitor_pessoa AS string) AS id_zona_titulo_eleitor,
    CAST(num_secao_tit_eleitor_pessoa AS string) AS id_secao_titulo_eleitor,
    CAST(cod_termo___matricula__certid_pessoa AS string) AS id_termi_matricula_certidao,
    CAST(num_identidade_pessoa AS string) AS rg,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_pessoa_0601`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_certidao_civil_pessoa AS string) AS id_certidao_civil,
    CAST(nom_cartorio_pessoa AS string) AS cartorio_certidao,
    CAST(cod_livro_termo_certid_pessoa AS string) AS livro_certidao_obito_excluido,
    CAST(cod_folha_termo_certid_pessoa AS string) AS folha_certidao,
    CAST(vazio_2 AS string) AS vazio,
    CAST(dta_emissao_certid_pessoa AS date) AS data_emissao_certidao,
    CAST(sig_uf_certid_pessoa AS string) AS sigla_uf_certidao,
    CAST(nom_munic_certid_pessoa AS string) AS municipio_certidao,
    CAST(cod_ibge_munic_certid_pessoa AS string) AS id_municipio_certidao,
    CAST(cod_cartorio_certid_pessoa AS string) AS id_cartorio_certidao,
    CAST(num_cpf_pessoa AS string) AS cpf,
    CAST(vazio_3 AS string) AS vazio,
    CAST(cod_complemento_pessoa AS string) AS id_complemento_rg,
    CAST(dta_emissao_ident_pessoa AS date) AS data_emissao_rg,
    CAST(sig_uf_ident_pessoa AS string) AS sigla_uf_rg,
    CAST(sig_orgao_emissor_pessoa AS string) AS orgao_emissor_rg,
    CAST(num_cart_trab_prev_soc_pessoa AS string) AS id_carteira_trabalho,
    CAST(num_serie_trab_prev_soc_pessoa AS string) AS id_serie_carteira_trabalho,
    CAST(dta_emissao_cart_trab_pessoa AS date) AS data_emissao_carteira_trabalho,
    CAST(sig_uf_cart_trab_pessoa AS string) AS sigla_uf_carteira_trabalho,
    CAST(num_titulo_eleitor_pessoa AS string) AS id_titulo_eleitor,
    CAST(num_zona_tit_eleitor_pessoa AS string) AS id_zona_titulo_eleitor,
    CAST(num_secao_tit_eleitor_pessoa AS string) AS id_secao_titulo_eleitor,
    CAST(cod_termo___matricula__certid_pessoa AS string) AS id_termi_matricula_certidao,
    CAST(num_identidade_pessoa AS string) AS rg,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_pessoa_0603`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_certidao_civil_pessoa AS string) AS id_certidao_civil,
    CAST(nom_cartorio_pessoa AS string) AS cartorio_certidao,
    CAST(cod_livro_termo_certid_pessoa AS string) AS livro_certidao_obito_excluido,
    CAST(cod_folha_termo_certid_pessoa AS string) AS folha_certidao,
    CAST(vazio_2 AS string) AS vazio,
    CAST(dta_emissao_certid_pessoa AS date) AS data_emissao_certidao,
    CAST(sig_uf_certid_pessoa AS string) AS sigla_uf_certidao,
    CAST(nom_munic_certid_pessoa AS string) AS municipio_certidao,
    CAST(cod_ibge_munic_certid_pessoa AS string) AS id_municipio_certidao,
    CAST(cod_cartorio_certid_pessoa AS string) AS id_cartorio_certidao,
    CAST(num_cpf_pessoa AS string) AS cpf,
    CAST(vazio_3 AS string) AS vazio,
    CAST(cod_complemento_pessoa AS string) AS id_complemento_rg,
    CAST(dta_emissao_ident_pessoa AS date) AS data_emissao_rg,
    CAST(sig_uf_ident_pessoa AS string) AS sigla_uf_rg,
    CAST(sig_orgao_emissor_pessoa AS string) AS orgao_emissor_rg,
    CAST(num_cart_trab_prev_soc_pessoa AS string) AS id_carteira_trabalho,
    CAST(num_serie_trab_prev_soc_pessoa AS string) AS id_serie_carteira_trabalho,
    CAST(dta_emissao_cart_trab_pessoa AS date) AS data_emissao_carteira_trabalho,
    CAST(sig_uf_cart_trab_pessoa AS string) AS sigla_uf_carteira_trabalho,
    CAST(num_titulo_eleitor_pessoa AS string) AS id_titulo_eleitor,
    CAST(num_zona_tit_eleitor_pessoa AS string) AS id_zona_titulo_eleitor,
    CAST(num_secao_tit_eleitor_pessoa AS string) AS id_secao_titulo_eleitor,
    CAST(cod_termo___matricula__certid_pessoa AS string) AS id_termi_matricula_certidao,
    CAST(num_identidade_pessoa AS string) AS rg,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_pessoa_0604`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_certidao_civil_pessoa AS string) AS id_certidao_civil,
    CAST(nom_cartorio_pessoa AS string) AS cartorio_certidao,
    CAST(cod_livro_termo_certid_pessoa AS string) AS livro_certidao_obito_excluido,
    CAST(cod_folha_termo_certid_pessoa AS string) AS folha_certidao,
    CAST(vazio_2 AS string) AS vazio,
    CAST(dta_emissao_certid_pessoa AS date) AS data_emissao_certidao,
    CAST(sig_uf_certid_pessoa AS string) AS sigla_uf_certidao,
    CAST(nom_munic_certid_pessoa AS string) AS municipio_certidao,
    CAST(cod_ibge_munic_certid_pessoa AS string) AS id_municipio_certidao,
    CAST(cod_cartorio_certid_pessoa AS string) AS id_cartorio_certidao,
    CAST(num_cpf_pessoa AS string) AS cpf,
    CAST(vazio_3 AS string) AS vazio,
    CAST(cod_complemento_pessoa AS string) AS id_complemento_rg,
    CAST(dta_emissao_ident_pessoa AS date) AS data_emissao_rg,
    CAST(sig_uf_ident_pessoa AS string) AS sigla_uf_rg,
    CAST(sig_orgao_emissor_pessoa AS string) AS orgao_emissor_rg,
    CAST(num_cart_trab_prev_soc_pessoa AS string) AS id_carteira_trabalho,
    CAST(num_serie_trab_prev_soc_pessoa AS string) AS id_serie_carteira_trabalho,
    CAST(dta_emissao_cart_trab_pessoa AS date) AS data_emissao_carteira_trabalho,
    CAST(sig_uf_cart_trab_pessoa AS string) AS sigla_uf_carteira_trabalho,
    CAST(num_titulo_eleitor_pessoa AS string) AS id_titulo_eleitor,
    CAST(num_zona_tit_eleitor_pessoa AS string) AS id_zona_titulo_eleitor,
    CAST(num_secao_tit_eleitor_pessoa AS string) AS id_secao_titulo_eleitor,
    CAST(cod_termo___matricula__certid_pessoa AS string) AS id_termi_matricula_certidao,
    CAST(num_identidade_pessoa AS string) AS rg,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_pessoa_0609`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_certidao_civil_pessoa AS string) AS id_certidao_civil,
    CAST(nom_cartorio_pessoa AS string) AS cartorio_certidao,
    CAST(cod_livro_termo_certid_pessoa AS string) AS livro_certidao_obito_excluido,
    CAST(cod_folha_termo_certid_pessoa AS string) AS folha_certidao,
    CAST(vazio_2 AS string) AS vazio,
    CAST(dta_emissao_certid_pessoa AS date) AS data_emissao_certidao,
    CAST(sig_uf_certid_pessoa AS string) AS sigla_uf_certidao,
    CAST(nom_munic_certid_pessoa AS string) AS municipio_certidao,
    CAST(cod_ibge_munic_certid_pessoa AS string) AS id_municipio_certidao,
    CAST(cod_cartorio_certid_pessoa AS string) AS id_cartorio_certidao,
    CAST(num_cpf_pessoa AS string) AS cpf,
    CAST(vazio_3 AS string) AS vazio,
    CAST(cod_complemento_pessoa AS string) AS id_complemento_rg,
    CAST(dta_emissao_ident_pessoa AS date) AS data_emissao_rg,
    CAST(sig_uf_ident_pessoa AS string) AS sigla_uf_rg,
    CAST(sig_orgao_emissor_pessoa AS string) AS orgao_emissor_rg,
    CAST(num_cart_trab_prev_soc_pessoa AS string) AS id_carteira_trabalho,
    CAST(num_serie_trab_prev_soc_pessoa AS string) AS id_serie_carteira_trabalho,
    CAST(dta_emissao_cart_trab_pessoa AS date) AS data_emissao_carteira_trabalho,
    CAST(sig_uf_cart_trab_pessoa AS string) AS sigla_uf_carteira_trabalho,
    CAST(num_titulo_eleitor_pessoa AS string) AS id_titulo_eleitor,
    CAST(num_zona_tit_eleitor_pessoa AS string) AS id_zona_titulo_eleitor,
    CAST(num_secao_tit_eleitor_pessoa AS string) AS id_secao_titulo_eleitor,
    CAST(cod_termo___matricula__certid_pessoa AS string) AS id_termi_matricula_certidao,
    CAST(num_identidade_pessoa AS string) AS rg,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_pessoa_0612`

