
SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(num_membro_fmla AS INT64) AS membros_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(ind_ptab_desat_inep_memb AS STRING) AS ptab_desativacao_inep,
    CAST(ind_pmig_cpo_obr_memb AS STRING) AS pmig_campo_obrigatorio_nao_preenchido,
    CAST(ind_pmig_sem_doc_memb AS STRING) AS pmig_sem_nunhuma_documentacao,
    CAST(ind_pmig_rf_cpf_eleitor_memb AS STRING) AS pmig_responsavel_sem_cpf_titulo_eleitor,
    CAST(ind_pmig_rf_cpf_inv_memb AS STRING) AS pmig_responsavel_cpf_invalido,
    CAST(ind_pmig_rf_cpf_mult_memb AS STRING) AS pmig_reponsavel_cpf_multiplicidade,
    CAST(ind_pmig_memb_cpf_mult_memb AS STRING) AS pmig_cpf_multiplicidade,
    CAST(ind_pmig_rf_cpf_titular_memb AS STRING) AS pmig_responsavel_cpf_divergencia_titularidade,
    CAST(ind_pmig_memb_cpf_titular_memb AS STRING) AS pmig_cpf_divergencia_titularidade,
    CAST(ind_pmig_rf_eleitor_inv_memb AS STRING) AS pmig_responsavel_titulo_eleitor_invalido,
    CAST(ind_pmig_rf_eleitor_mult_memb AS STRING) AS pmig_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_memb_cpf_inv_memb AS STRING) AS pmig_cpf_invalido,
    CAST(ind_pmig_memb_eleitor_mult_memb AS STRING) AS pmig_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_rf_idade_16_memb AS STRING) AS pmig_responsavel_idade_inferior_16_anos,
    CAST(ind_ptrn_memb_inep_memb AS STRING) AS ptrn_verficacao_dados_inep,
    CAST(ind_ptrn_memb_parente_memb AS STRING) AS ptrn_sem_relacao_parentesco,
    CAST(ind_paud_cpo_obr_memb AS STRING) AS paud_campo_obrigatorio_nao_preenchido,
    CAST(ind_paud_rf_cpf_eleitor_memb AS STRING) AS paud_responsavel_sem_cpf_tiluto_eleitor,
    CAST(ind_paud_rf_cpf_inv_memb AS STRING) AS paud_responsavel_cpf_invalido,
    CAST(ind_paud_rf_cpf_mult_memb AS STRING) AS paud_responsavel_cpf_multiplicidade,
    CAST(ind_paud_memb_cpf_mult_memb AS STRING) AS paud_cpf_multiplicidade,
    CAST(ind_paud_rf_cpf_titular_memb AS STRING) AS paud_responsavel_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_titular_memb AS STRING) AS paud_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_inv_memb AS STRING) AS paud_cpf_invalido,
    CAST(ind_paud_memb_eleitor_inv_memb AS STRING) AS paud_titulo_eleitor_invalido,
    CAST(ind_paud_rf_eleitor_inv_memb AS STRING) AS paud_responsavel_titulo_eleitor_invalido,
    CAST(ind_paud_memb_eleitor_mult_memb AS STRING) AS paud_titulo_eleitor_multiplicidade,
    CAST(ind_paud_rf_idade_16_memb AS STRING) AS paud_responsavel_idade_inferior_16_anos,
    CAST(ind_paud_rejei_memb AS STRING) AS paud_rejeicao_inclusao_atualizacao_dados_cadastrais,
    CAST(ind_otrn_outro_mun_pes AS STRING) AS otrn_transferida_outro_municipio,
    CAST(ind_otrn_nova_pes AS STRING) AS otrn_transferida_este_municipio_nova_familia,
    CAST(ind_otrn_exist_pes AS STRING) AS otrn_transferida_este_municipio_familia_existente,
    CAST(ind_otrn_outra_pes AS STRING) AS otrn_transferida_outra_familia,
    CAST(ind_osrg_sem_certidao_pes AS STRING) AS osrg_registrada_sem_cetidao_civil,
    CAST(ind_osrg_sem_registro_pes AS STRING) AS osrg_nao_registrada_cartorio,
    CAST(ind_osrg_nao_sabe_pes AS STRING) AS osrg_nao_sabe_registrada_cartorio,
    CAST(ind_paud_mbo_cad_com_cert_obit AS STRING) AS paud_cadatrado_com_certidao_obito,
    CAST(ind_oaud_memb_ind_obto_neg AS STRING) AS oaud_indicativo_obito,
    CAST(ind_paud_rf_eleitor_mult_memb AS STRING) AS paud_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_oaud_memb_mult_ctps AS STRING) AS oaud_carteira_trabalho_multiplicidade,
    CAST(ind_oaud_memb_mult_rcn AS STRING) AS oaud_certidao_nascimento_multiplicidade,
    CAST(ind_oaud_memb_mult_rg AS STRING) AS oaud_rg_multiplicidade,
    CAST(ind_paud_cpf_susp_receita AS STRING) AS paud_cpf_suspenso_base_receita_federal,
    CAST(ind_paud_cpf_cancel_receita AS STRING) AS paud_cpf_cancelado_base_receita_federal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_membro_0601`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(num_membro_fmla AS INT64) AS membros_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(ind_ptab_desat_inep_memb AS STRING) AS ptab_desativacao_inep,
    CAST(ind_pmig_cpo_obr_memb AS STRING) AS pmig_campo_obrigatorio_nao_preenchido,
    CAST(ind_pmig_sem_doc_memb AS STRING) AS pmig_sem_nunhuma_documentacao,
    CAST(ind_pmig_rf_cpf_eleitor_memb AS STRING) AS pmig_responsavel_sem_cpf_titulo_eleitor,
    CAST(ind_pmig_rf_cpf_inv_memb AS STRING) AS pmig_responsavel_cpf_invalido,
    CAST(ind_pmig_rf_cpf_mult_memb AS STRING) AS pmig_reponsavel_cpf_multiplicidade,
    CAST(ind_pmig_memb_cpf_mult_memb AS STRING) AS pmig_cpf_multiplicidade,
    CAST(ind_pmig_rf_cpf_titular_memb AS STRING) AS pmig_responsavel_cpf_divergencia_titularidade,
    CAST(ind_pmig_memb_cpf_titular_memb AS STRING) AS pmig_cpf_divergencia_titularidade,
    CAST(ind_pmig_rf_eleitor_inv_memb AS STRING) AS pmig_responsavel_titulo_eleitor_invalido,
    CAST(ind_pmig_rf_eleitor_mult_memb AS STRING) AS pmig_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_memb_cpf_inv_memb AS STRING) AS pmig_cpf_invalido,
    CAST(ind_pmig_memb_eleitor_mult_memb AS STRING) AS pmig_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_rf_idade_16_memb AS STRING) AS pmig_responsavel_idade_inferior_16_anos,
    CAST(ind_ptrn_memb_inep_memb AS STRING) AS ptrn_verficacao_dados_inep,
    CAST(ind_ptrn_memb_parente_memb AS STRING) AS ptrn_sem_relacao_parentesco,
    CAST(ind_paud_cpo_obr_memb AS STRING) AS paud_campo_obrigatorio_nao_preenchido,
    CAST(ind_paud_rf_cpf_eleitor_memb AS STRING) AS paud_responsavel_sem_cpf_tiluto_eleitor,
    CAST(ind_paud_rf_cpf_inv_memb AS STRING) AS paud_responsavel_cpf_invalido,
    CAST(ind_paud_rf_cpf_mult_memb AS STRING) AS paud_responsavel_cpf_multiplicidade,
    CAST(ind_paud_memb_cpf_mult_memb AS STRING) AS paud_cpf_multiplicidade,
    CAST(ind_paud_rf_cpf_titular_memb AS STRING) AS paud_responsavel_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_titular_memb AS STRING) AS paud_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_inv_memb AS STRING) AS paud_cpf_invalido,
    CAST(ind_paud_memb_eleitor_inv_memb AS STRING) AS paud_titulo_eleitor_invalido,
    CAST(ind_paud_rf_eleitor_inv_memb AS STRING) AS paud_responsavel_titulo_eleitor_invalido,
    CAST(ind_paud_memb_eleitor_mult_memb AS STRING) AS paud_titulo_eleitor_multiplicidade,
    CAST(ind_paud_rf_idade_16_memb AS STRING) AS paud_responsavel_idade_inferior_16_anos,
    CAST(ind_paud_rejei_memb AS STRING) AS paud_rejeicao_inclusao_atualizacao_dados_cadastrais,
    CAST(ind_otrn_outro_mun_pes AS STRING) AS otrn_transferida_outro_municipio,
    CAST(ind_otrn_nova_pes AS STRING) AS otrn_transferida_este_municipio_nova_familia,
    CAST(ind_otrn_exist_pes AS STRING) AS otrn_transferida_este_municipio_familia_existente,
    CAST(ind_otrn_outra_pes AS STRING) AS otrn_transferida_outra_familia,
    CAST(ind_osrg_sem_certidao_pes AS STRING) AS osrg_registrada_sem_cetidao_civil,
    CAST(ind_osrg_sem_registro_pes AS STRING) AS osrg_nao_registrada_cartorio,
    CAST(ind_osrg_nao_sabe_pes AS STRING) AS osrg_nao_sabe_registrada_cartorio,
    CAST(ind_paud_mbo_cad_com_cert_obit AS STRING) AS paud_cadatrado_com_certidao_obito,
    CAST(ind_oaud_memb_ind_obto_neg AS STRING) AS oaud_indicativo_obito,
    CAST(ind_paud_rf_eleitor_mult_memb AS STRING) AS paud_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_oaud_memb_mult_ctps AS STRING) AS oaud_carteira_trabalho_multiplicidade,
    CAST(ind_oaud_memb_mult_rcn AS STRING) AS oaud_certidao_nascimento_multiplicidade,
    CAST(ind_oaud_memb_mult_rg AS STRING) AS oaud_rg_multiplicidade,
    CAST(ind_paud_cpf_cancel_receita AS STRING) AS paud_cpf_cancelado_base_receita_federal,
    CAST(ind_paud_cpf_susp_receita AS STRING) AS paud_cpf_suspenso_base_receita_federal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_membro_0603`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(num_membro_fmla AS INT64) AS membros_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(ind_ptab_desat_inep_memb AS STRING) AS ptab_desativacao_inep,
    CAST(ind_pmig_cpo_obr_memb AS STRING) AS pmig_campo_obrigatorio_nao_preenchido,
    CAST(ind_pmig_sem_doc_memb AS STRING) AS pmig_sem_nunhuma_documentacao,
    CAST(ind_pmig_rf_cpf_eleitor_memb AS STRING) AS pmig_responsavel_sem_cpf_titulo_eleitor,
    CAST(ind_pmig_rf_cpf_inv_memb AS STRING) AS pmig_responsavel_cpf_invalido,
    CAST(ind_pmig_rf_cpf_mult_memb AS STRING) AS pmig_reponsavel_cpf_multiplicidade,
    CAST(ind_pmig_memb_cpf_mult_memb AS STRING) AS pmig_cpf_multiplicidade,
    CAST(ind_pmig_rf_cpf_titular_memb AS STRING) AS pmig_responsavel_cpf_divergencia_titularidade,
    CAST(ind_pmig_memb_cpf_titular_memb AS STRING) AS pmig_cpf_divergencia_titularidade,
    CAST(ind_pmig_rf_eleitor_inv_memb AS STRING) AS pmig_responsavel_titulo_eleitor_invalido,
    CAST(ind_pmig_rf_eleitor_mult_memb AS STRING) AS pmig_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_memb_cpf_inv_memb AS STRING) AS pmig_cpf_invalido,
    CAST(ind_pmig_memb_eleitor_mult_memb AS STRING) AS pmig_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_rf_idade_16_memb AS STRING) AS pmig_responsavel_idade_inferior_16_anos,
    CAST(ind_ptrn_memb_inep_memb AS STRING) AS ptrn_verficacao_dados_inep,
    CAST(ind_ptrn_memb_parente_memb AS STRING) AS ptrn_sem_relacao_parentesco,
    CAST(ind_paud_cpo_obr_memb AS STRING) AS paud_campo_obrigatorio_nao_preenchido,
    CAST(ind_paud_rf_cpf_eleitor_memb AS STRING) AS paud_responsavel_sem_cpf_tiluto_eleitor,
    CAST(ind_paud_rf_cpf_inv_memb AS STRING) AS paud_responsavel_cpf_invalido,
    CAST(ind_paud_rf_cpf_mult_memb AS STRING) AS paud_responsavel_cpf_multiplicidade,
    CAST(ind_paud_memb_cpf_mult_memb AS STRING) AS paud_cpf_multiplicidade,
    CAST(ind_paud_rf_cpf_titular_memb AS STRING) AS paud_responsavel_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_titular_memb AS STRING) AS paud_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_inv_memb AS STRING) AS paud_cpf_invalido,
    CAST(ind_paud_memb_eleitor_inv_memb AS STRING) AS paud_titulo_eleitor_invalido,
    CAST(ind_paud_rf_eleitor_inv_memb AS STRING) AS paud_responsavel_titulo_eleitor_invalido,
    CAST(ind_paud_memb_eleitor_mult_memb AS STRING) AS paud_titulo_eleitor_multiplicidade,
    CAST(ind_paud_rf_idade_16_memb AS STRING) AS paud_responsavel_idade_inferior_16_anos,
    CAST(ind_paud_rejei_memb AS STRING) AS paud_rejeicao_inclusao_atualizacao_dados_cadastrais,
    CAST(ind_otrn_outro_mun_pes AS STRING) AS otrn_transferida_outro_municipio,
    CAST(ind_otrn_nova_pes AS STRING) AS otrn_transferida_este_municipio_nova_familia,
    CAST(ind_otrn_exist_pes AS STRING) AS otrn_transferida_este_municipio_familia_existente,
    CAST(ind_otrn_outra_pes AS STRING) AS otrn_transferida_outra_familia,
    CAST(ind_osrg_sem_certidao_pes AS STRING) AS osrg_registrada_sem_cetidao_civil,
    CAST(ind_osrg_sem_registro_pes AS STRING) AS osrg_nao_registrada_cartorio,
    CAST(ind_osrg_nao_sabe_pes AS STRING) AS osrg_nao_sabe_registrada_cartorio,
    CAST(ind_paud_mbo_cad_com_cert_obit AS STRING) AS paud_cadatrado_com_certidao_obito,
    CAST(ind_oaud_memb_ind_obto_neg AS STRING) AS oaud_indicativo_obito,
    CAST(ind_paud_rf_eleitor_mult_memb AS STRING) AS paud_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_oaud_memb_mult_ctps AS STRING) AS oaud_carteira_trabalho_multiplicidade,
    CAST(ind_oaud_memb_mult_rcn AS STRING) AS oaud_certidao_nascimento_multiplicidade,
    CAST(ind_oaud_memb_mult_rg AS STRING) AS oaud_rg_multiplicidade,
    CAST(ind_paud_cpf_cancel_receita AS STRING) AS paud_cpf_cancelado_base_receita_federal,
    CAST(ind_paud_cpf_susp_receita AS STRING) AS paud_cpf_suspenso_base_receita_federal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_membro_0604`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(num_membro_fmla AS INT64) AS membros_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(ind_ptab_desat_inep_memb AS STRING) AS ptab_desativacao_inep,
    CAST(ind_pmig_cpo_obr_memb AS STRING) AS pmig_campo_obrigatorio_nao_preenchido,
    CAST(ind_pmig_sem_doc_memb AS STRING) AS pmig_sem_nunhuma_documentacao,
    CAST(ind_pmig_rf_cpf_eleitor_memb AS STRING) AS pmig_responsavel_sem_cpf_titulo_eleitor,
    CAST(ind_pmig_rf_cpf_inv_memb AS STRING) AS pmig_responsavel_cpf_invalido,
    CAST(ind_pmig_rf_cpf_mult_memb AS STRING) AS pmig_reponsavel_cpf_multiplicidade,
    CAST(ind_pmig_memb_cpf_mult_memb AS STRING) AS pmig_cpf_multiplicidade,
    CAST(ind_pmig_rf_cpf_titular_memb AS STRING) AS pmig_responsavel_cpf_divergencia_titularidade,
    CAST(ind_pmig_memb_cpf_titular_memb AS STRING) AS pmig_cpf_divergencia_titularidade,
    CAST(ind_pmig_rf_eleitor_inv_memb AS STRING) AS pmig_responsavel_titulo_eleitor_invalido,
    CAST(ind_pmig_rf_eleitor_mult_memb AS STRING) AS pmig_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_memb_cpf_inv_memb AS STRING) AS pmig_cpf_invalido,
    CAST(ind_pmig_memb_eleitor_mult_memb AS STRING) AS pmig_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_rf_idade_16_memb AS STRING) AS pmig_responsavel_idade_inferior_16_anos,
    CAST(ind_ptrn_memb_inep_memb AS STRING) AS ptrn_verficacao_dados_inep,
    CAST(ind_ptrn_memb_parente_memb AS STRING) AS ptrn_sem_relacao_parentesco,
    CAST(ind_paud_cpo_obr_memb AS STRING) AS paud_campo_obrigatorio_nao_preenchido,
    CAST(ind_paud_rf_cpf_eleitor_memb AS STRING) AS paud_responsavel_sem_cpf_tiluto_eleitor,
    CAST(ind_paud_rf_cpf_inv_memb AS STRING) AS paud_responsavel_cpf_invalido,
    CAST(ind_paud_rf_cpf_mult_memb AS STRING) AS paud_responsavel_cpf_multiplicidade,
    CAST(ind_paud_memb_cpf_mult_memb AS STRING) AS paud_cpf_multiplicidade,
    CAST(ind_paud_rf_cpf_titular_memb AS STRING) AS paud_responsavel_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_titular_memb AS STRING) AS paud_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_inv_memb AS STRING) AS paud_cpf_invalido,
    CAST(ind_paud_memb_eleitor_inv_memb AS STRING) AS paud_titulo_eleitor_invalido,
    CAST(ind_paud_rf_eleitor_inv_memb AS STRING) AS paud_responsavel_titulo_eleitor_invalido,
    CAST(ind_paud_memb_eleitor_mult_memb AS STRING) AS paud_titulo_eleitor_multiplicidade,
    CAST(ind_paud_rf_idade_16_memb AS STRING) AS paud_responsavel_idade_inferior_16_anos,
    CAST(ind_paud_rejei_memb AS STRING) AS paud_rejeicao_inclusao_atualizacao_dados_cadastrais,
    CAST(ind_otrn_outro_mun_pes AS STRING) AS otrn_transferida_outro_municipio,
    CAST(ind_otrn_nova_pes AS STRING) AS otrn_transferida_este_municipio_nova_familia,
    CAST(ind_otrn_exist_pes AS STRING) AS otrn_transferida_este_municipio_familia_existente,
    CAST(ind_otrn_outra_pes AS STRING) AS otrn_transferida_outra_familia,
    CAST(ind_osrg_sem_certidao_pes AS STRING) AS osrg_registrada_sem_cetidao_civil,
    CAST(ind_osrg_sem_registro_pes AS STRING) AS osrg_nao_registrada_cartorio,
    CAST(ind_osrg_nao_sabe_pes AS STRING) AS osrg_nao_sabe_registrada_cartorio,
    CAST(ind_paud_mbo_cad_com_cert_obit AS STRING) AS paud_cadatrado_com_certidao_obito,
    CAST(ind_oaud_memb_ind_obto_neg AS STRING) AS oaud_indicativo_obito,
    CAST(ind_paud_rf_eleitor_mult_memb AS STRING) AS paud_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_oaud_memb_mult_ctps AS STRING) AS oaud_carteira_trabalho_multiplicidade,
    CAST(ind_oaud_memb_mult_rcn AS STRING) AS oaud_certidao_nascimento_multiplicidade,
    CAST(ind_oaud_memb_mult_rg AS STRING) AS oaud_rg_multiplicidade,
    CAST(ind_paud_cpf_cancel_receita AS STRING) AS paud_cpf_cancelado_base_receita_federal,
    CAST(ind_paud_cpf_susp_receita AS STRING) AS paud_cpf_suspenso_base_receita_federal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_membro_0609`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(num_membro_fmla AS INT64) AS membros_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(ind_ptab_desat_inep_memb AS STRING) AS ptab_desativacao_inep,
    CAST(ind_pmig_cpo_obr_memb AS STRING) AS pmig_campo_obrigatorio_nao_preenchido,
    CAST(ind_pmig_sem_doc_memb AS STRING) AS pmig_sem_nunhuma_documentacao,
    CAST(ind_pmig_rf_cpf_eleitor_memb AS STRING) AS pmig_responsavel_sem_cpf_titulo_eleitor,
    CAST(ind_pmig_rf_cpf_inv_memb AS STRING) AS pmig_responsavel_cpf_invalido,
    CAST(ind_pmig_rf_cpf_mult_memb AS STRING) AS pmig_reponsavel_cpf_multiplicidade,
    CAST(ind_pmig_memb_cpf_mult_memb AS STRING) AS pmig_cpf_multiplicidade,
    CAST(ind_pmig_rf_cpf_titular_memb AS STRING) AS pmig_responsavel_cpf_divergencia_titularidade,
    CAST(ind_pmig_memb_cpf_titular_memb AS STRING) AS pmig_cpf_divergencia_titularidade,
    CAST(ind_pmig_rf_eleitor_inv_memb AS STRING) AS pmig_responsavel_titulo_eleitor_invalido,
    CAST(ind_pmig_rf_eleitor_mult_memb AS STRING) AS pmig_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_memb_cpf_inv_memb AS STRING) AS pmig_cpf_invalido,
    CAST(ind_pmig_memb_eleitor_mult_memb AS STRING) AS pmig_titulo_eleitor_multiplicidade,
    CAST(ind_pmig_rf_idade_16_memb AS STRING) AS pmig_responsavel_idade_inferior_16_anos,
    CAST(ind_ptrn_memb_inep_memb AS STRING) AS ptrn_verficacao_dados_inep,
    CAST(ind_ptrn_memb_parente_memb AS STRING) AS ptrn_sem_relacao_parentesco,
    CAST(ind_paud_cpo_obr_memb AS STRING) AS paud_campo_obrigatorio_nao_preenchido,
    CAST(ind_paud_rf_cpf_eleitor_memb AS STRING) AS paud_responsavel_sem_cpf_tiluto_eleitor,
    CAST(ind_paud_rf_cpf_inv_memb AS STRING) AS paud_responsavel_cpf_invalido,
    CAST(ind_paud_rf_cpf_mult_memb AS STRING) AS paud_responsavel_cpf_multiplicidade,
    CAST(ind_paud_memb_cpf_mult_memb AS STRING) AS paud_cpf_multiplicidade,
    CAST(ind_paud_rf_cpf_titular_memb AS STRING) AS paud_responsavel_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_titular_memb AS STRING) AS paud_cpf_divergencia_titularidade,
    CAST(ind_paud_memb_cpf_inv_memb AS STRING) AS paud_cpf_invalido,
    CAST(ind_paud_memb_eleitor_inv_memb AS STRING) AS paud_titulo_eleitor_invalido,
    CAST(ind_paud_rf_eleitor_inv_memb AS STRING) AS paud_responsavel_titulo_eleitor_invalido,
    CAST(ind_paud_memb_eleitor_mult_memb AS STRING) AS paud_titulo_eleitor_multiplicidade,
    CAST(ind_paud_rf_idade_16_memb AS STRING) AS paud_responsavel_idade_inferior_16_anos,
    CAST(ind_paud_rejei_memb AS STRING) AS paud_rejeicao_inclusao_atualizacao_dados_cadastrais,
    CAST(ind_otrn_outro_mun_pes AS STRING) AS otrn_transferida_outro_municipio,
    CAST(ind_otrn_nova_pes AS STRING) AS otrn_transferida_este_municipio_nova_familia,
    CAST(ind_otrn_exist_pes AS STRING) AS otrn_transferida_este_municipio_familia_existente,
    CAST(ind_otrn_outra_pes AS STRING) AS otrn_transferida_outra_familia,
    CAST(ind_osrg_sem_certidao_pes AS STRING) AS osrg_registrada_sem_cetidao_civil,
    CAST(ind_osrg_sem_registro_pes AS STRING) AS osrg_nao_registrada_cartorio,
    CAST(ind_osrg_nao_sabe_pes AS STRING) AS osrg_nao_sabe_registrada_cartorio,
    CAST(ind_paud_mbo_cad_com_cert_obit AS STRING) AS paud_cadatrado_com_certidao_obito,
    CAST(ind_oaud_memb_ind_obto_neg AS STRING) AS oaud_indicativo_obito,
    CAST(ind_paud_rf_eleitor_mult_memb AS STRING) AS paud_responsavel_titulo_eleitor_multiplicidade,
    CAST(ind_oaud_memb_mult_ctps AS STRING) AS oaud_carteira_trabalho_multiplicidade,
    CAST(ind_oaud_memb_mult_rcn AS STRING) AS oaud_certidao_nascimento_multiplicidade,
    CAST(ind_oaud_memb_mult_rg AS STRING) AS oaud_rg_multiplicidade,
    CAST(ind_paud_cpf_cancel_receita AS STRING) AS paud_cpf_cancelado_base_receita_federal,
    CAST(ind_paud_cpf_susp_receita AS STRING) AS paud_cpf_suspenso_base_receita_federal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.documento_membro_0612`

