
SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_familia_indigena_fam AS string) AS id_familia_indigena,
    CAST(cod_povo_indigena_fam AS string) AS id_povo_indigena,
    CAST(nom_povo_indigena_fam AS string) AS povo_indigena,
    CAST(vazio2 AS string) AS vazio_2,
    CAST(cod_indigena_reside_fam AS string) AS id_indigena_residente,
    CAST(cod_reserva_indigena_fam AS string) AS id_reserva_indigena,
    CAST(nom_reserva_indigena_fam AS string) AS reserva_indigena,
    CAST(ind_reserva_indigena_fam AS string) AS nao_sabe_reserva_indigena,
    CAST(ind_familia_quilombola_fam AS string) AS familia_quilombola,
    CAST(cod_comunidade_quilombola_fam AS string) AS id_comunidade_quilombola,
    CAST(nom_comunidade_quilombola_fam AS string) AS comunidade_quilombola,
    CAST(ind_comunidade_quilombola_fam AS string) AS nao_sabe_comunidade_quilombola,
    CAST(qtd_pessoas_domic_fam AS int64) AS pessoas_domicilio,
    CAST(qtd_familias_domic_fam AS int64) AS familias_domicilio,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS int64) AS pessoas_internadas_0_17_anos,
    CAST(ind_pessoa_inter_0_17_anos_fam AS string) AS nao_tem_pessoas_internadas_0_17_anos,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS int64) AS pessoas_internadas_18_59_anos,
    CAST(ind_pessoa_inter_18_59_anos_fam AS string) AS nao_tem_pessoas_internadas_18_59_anos,
    CAST(qtd_pessoa_inter_60_anos_fam AS int64) AS pessoas_internadas_mais_60_anos,
    CAST(ind_pessoa_inter_60_anos_fam AS string) AS nao_tem_pessoas_internadas_mais_60_anos,
    CAST(val_desp_energia_fam AS int64) AS despesa_energia,
    CAST(ind_desp_energia_fam AS string) AS nao_tem_despesa_energia,
    CAST(val_desp_agua_esgoto_fam AS int64) AS despesa_agua_esgoto,
    CAST(ind_desp_agua_esgoto_fam AS string) AS nao_tem_despesa_agua_esgoto,
    CAST(val_desp_gas_fam AS int64) AS despesa_gas,
    CAST(ind_desp_gas_fam AS string) AS nao_tem_despesa_gas,
    CAST(val_desp_alimentacao_fam AS int64) AS despesa_alimentacao,
    CAST(ind_desp_alimentacao_fam AS string) AS nao_tem_despesa_alimentacao,
    CAST(val_desp_transpor_fam AS int64) AS despesa_transporte,
    CAST(ind_desp_transpor_fam AS string) AS nao_tem_despesa_transporte,
    CAST(val_desp_aluguel_fam AS int64) AS despesa_aluguel,
    CAST(ind_desp_aluguel_fam AS string) AS nao_tem_despesa_aluguel,
    CAST(val_desp_medicamentos_fam AS int64) AS despesa_medicamentos,
    CAST(ind_desp_medicamentos_fam AS string) AS nao_tem_despesa_medicamentos,
    CAST(nom_estab_assist_saude_fam AS string) AS estabelecimento_saude,
    CAST(nu_estbo_saude AS string) AS id_estabelecimento_saude,
    CAST(nom_centro_assist_fam AS string) AS cras_creas,
    CAST(cod_centro_assist_fam AS string) AS id_cras_creas,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.familia_0601`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_familia_indigena_fam AS string) AS id_familia_indigena,
    CAST(cod_povo_indigena_fam AS string) AS id_povo_indigena,
    CAST(nom_povo_indigena_fam AS string) AS povo_indigena,
    CAST(vazio2 AS string) AS vazio_2,
    CAST(cod_indigena_reside_fam AS string) AS id_indigena_residente,
    CAST(cod_reserva_indigena_fam AS string) AS id_reserva_indigena,
    CAST(nom_reserva_indigena_fam AS string) AS reserva_indigena,
    CAST(ind_reserva_indigena_fam AS string) AS nao_sabe_reserva_indigena,
    CAST(ind_familia_quilombola_fam AS string) AS familia_quilombola,
    CAST(cod_comunidade_quilombola_fam AS string) AS id_comunidade_quilombola,
    CAST(nom_comunidade_quilombola_fam AS string) AS comunidade_quilombola,
    CAST(ind_comunidade_quilombola_fam AS string) AS nao_sabe_comunidade_quilombola,
    CAST(qtd_pessoas_domic_fam AS int64) AS pessoas_domicilio,
    CAST(qtd_familias_domic_fam AS int64) AS familias_domicilio,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS int64) AS pessoas_internadas_0_17_anos,
    CAST(ind_pessoa_inter_0_17_anos_fam AS string) AS nao_tem_pessoas_internadas_0_17_anos,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS int64) AS pessoas_internadas_18_59_anos,
    CAST(ind_pessoa_inter_18_59_anos_fam AS string) AS nao_tem_pessoas_internadas_18_59_anos,
    CAST(qtd_pessoa_inter_60_anos_fam AS int64) AS pessoas_internadas_mais_60_anos,
    CAST(ind_pessoa_inter_60_anos_fam AS string) AS nao_tem_pessoas_internadas_mais_60_anos,
    CAST(val_desp_energia_fam AS int64) AS despesa_energia,
    CAST(ind_desp_energia_fam AS string) AS nao_tem_despesa_energia,
    CAST(val_desp_agua_esgoto_fam AS int64) AS despesa_agua_esgoto,
    CAST(ind_desp_agua_esgoto_fam AS string) AS nao_tem_despesa_agua_esgoto,
    CAST(val_desp_gas_fam AS int64) AS despesa_gas,
    CAST(ind_desp_gas_fam AS string) AS nao_tem_despesa_gas,
    CAST(val_desp_alimentacao_fam AS int64) AS despesa_alimentacao,
    CAST(ind_desp_alimentacao_fam AS string) AS nao_tem_despesa_alimentacao,
    CAST(val_desp_transpor_fam AS int64) AS despesa_transporte,
    CAST(ind_desp_transpor_fam AS string) AS nao_tem_despesa_transporte,
    CAST(val_desp_aluguel_fam AS int64) AS despesa_aluguel,
    CAST(ind_desp_aluguel_fam AS string) AS nao_tem_despesa_aluguel,
    CAST(val_desp_medicamentos_fam AS int64) AS despesa_medicamentos,
    CAST(ind_desp_medicamentos_fam AS string) AS nao_tem_despesa_medicamentos,
    CAST(nom_estab_assist_saude_fam AS string) AS estabelecimento_saude,
    CAST(nu_estbo_saude AS string) AS id_estabelecimento_saude,
    CAST(nom_centro_assist_fam AS string) AS cras_creas,
    CAST(cod_centro_assist_fam AS string) AS id_cras_creas,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.familia_0603`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_familia_indigena_fam AS string) AS id_familia_indigena,
    CAST(cod_povo_indigena_fam AS string) AS id_povo_indigena,
    CAST(nom_povo_indigena_fam AS string) AS povo_indigena,
    CAST(vazio2 AS string) AS vazio_2,
    CAST(cod_indigena_reside_fam AS string) AS id_indigena_residente,
    CAST(cod_reserva_indigena_fam AS string) AS id_reserva_indigena,
    CAST(nom_reserva_indigena_fam AS string) AS reserva_indigena,
    CAST(ind_reserva_indigena_fam AS string) AS nao_sabe_reserva_indigena,
    CAST(ind_familia_quilombola_fam AS string) AS familia_quilombola,
    CAST(cod_comunidade_quilombola_fam AS string) AS id_comunidade_quilombola,
    CAST(nom_comunidade_quilombola_fam AS string) AS comunidade_quilombola,
    CAST(ind_comunidade_quilombola_fam AS string) AS nao_sabe_comunidade_quilombola,
    CAST(qtd_pessoas_domic_fam AS int64) AS pessoas_domicilio,
    CAST(qtd_familias_domic_fam AS int64) AS familias_domicilio,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS int64) AS pessoas_internadas_0_17_anos,
    CAST(ind_pessoa_inter_0_17_anos_fam AS string) AS nao_tem_pessoas_internadas_0_17_anos,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS int64) AS pessoas_internadas_18_59_anos,
    CAST(ind_pessoa_inter_18_59_anos_fam AS string) AS nao_tem_pessoas_internadas_18_59_anos,
    CAST(qtd_pessoa_inter_60_anos_fam AS int64) AS pessoas_internadas_mais_60_anos,
    CAST(ind_pessoa_inter_60_anos_fam AS string) AS nao_tem_pessoas_internadas_mais_60_anos,
    CAST(val_desp_energia_fam AS int64) AS despesa_energia,
    CAST(ind_desp_energia_fam AS string) AS nao_tem_despesa_energia,
    CAST(val_desp_agua_esgoto_fam AS int64) AS despesa_agua_esgoto,
    CAST(ind_desp_agua_esgoto_fam AS string) AS nao_tem_despesa_agua_esgoto,
    CAST(val_desp_gas_fam AS int64) AS despesa_gas,
    CAST(ind_desp_gas_fam AS string) AS nao_tem_despesa_gas,
    CAST(val_desp_alimentacao_fam AS int64) AS despesa_alimentacao,
    CAST(ind_desp_alimentacao_fam AS string) AS nao_tem_despesa_alimentacao,
    CAST(val_desp_transpor_fam AS int64) AS despesa_transporte,
    CAST(ind_desp_transpor_fam AS string) AS nao_tem_despesa_transporte,
    CAST(val_desp_aluguel_fam AS int64) AS despesa_aluguel,
    CAST(ind_desp_aluguel_fam AS string) AS nao_tem_despesa_aluguel,
    CAST(val_desp_medicamentos_fam AS int64) AS despesa_medicamentos,
    CAST(ind_desp_medicamentos_fam AS string) AS nao_tem_despesa_medicamentos,
    CAST(nom_estab_assist_saude_fam AS string) AS estabelecimento_saude,
    CAST(nu_estbo_saude AS string) AS id_estabelecimento_saude,
    CAST(nom_centro_assist_fam AS string) AS cras_creas,
    CAST(cod_centro_assist_fam AS string) AS id_cras_creas,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.familia_0604`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_familia_indigena_fam AS string) AS id_familia_indigena,
    CAST(cod_povo_indigena_fam AS string) AS id_povo_indigena,
    CAST(nom_povo_indigena_fam AS string) AS povo_indigena,
    CAST(vazio2 AS string) AS vazio_2,
    CAST(cod_indigena_reside_fam AS string) AS id_indigena_residente,
    CAST(cod_reserva_indigena_fam AS string) AS id_reserva_indigena,
    CAST(nom_reserva_indigena_fam AS string) AS reserva_indigena,
    CAST(ind_reserva_indigena_fam AS string) AS nao_sabe_reserva_indigena,
    CAST(ind_familia_quilombola_fam AS string) AS familia_quilombola,
    CAST(cod_comunidade_quilombola_fam AS string) AS id_comunidade_quilombola,
    CAST(nom_comunidade_quilombola_fam AS string) AS comunidade_quilombola,
    CAST(ind_comunidade_quilombola_fam AS string) AS nao_sabe_comunidade_quilombola,
    CAST(qtd_pessoas_domic_fam AS int64) AS pessoas_domicilio,
    CAST(qtd_familias_domic_fam AS int64) AS familias_domicilio,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS int64) AS pessoas_internadas_0_17_anos,
    CAST(ind_pessoa_inter_0_17_anos_fam AS string) AS nao_tem_pessoas_internadas_0_17_anos,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS int64) AS pessoas_internadas_18_59_anos,
    CAST(ind_pessoa_inter_18_59_anos_fam AS string) AS nao_tem_pessoas_internadas_18_59_anos,
    CAST(qtd_pessoa_inter_60_anos_fam AS int64) AS pessoas_internadas_mais_60_anos,
    CAST(ind_pessoa_inter_60_anos_fam AS string) AS nao_tem_pessoas_internadas_mais_60_anos,
    CAST(val_desp_energia_fam AS int64) AS despesa_energia,
    CAST(ind_desp_energia_fam AS string) AS nao_tem_despesa_energia,
    CAST(val_desp_agua_esgoto_fam AS int64) AS despesa_agua_esgoto,
    CAST(ind_desp_agua_esgoto_fam AS string) AS nao_tem_despesa_agua_esgoto,
    CAST(val_desp_gas_fam AS int64) AS despesa_gas,
    CAST(ind_desp_gas_fam AS string) AS nao_tem_despesa_gas,
    CAST(val_desp_alimentacao_fam AS int64) AS despesa_alimentacao,
    CAST(ind_desp_alimentacao_fam AS string) AS nao_tem_despesa_alimentacao,
    CAST(val_desp_transpor_fam AS int64) AS despesa_transporte,
    CAST(ind_desp_transpor_fam AS string) AS nao_tem_despesa_transporte,
    CAST(val_desp_aluguel_fam AS int64) AS despesa_aluguel,
    CAST(ind_desp_aluguel_fam AS string) AS nao_tem_despesa_aluguel,
    CAST(val_desp_medicamentos_fam AS int64) AS despesa_medicamentos,
    CAST(ind_desp_medicamentos_fam AS string) AS nao_tem_despesa_medicamentos,
    CAST(nom_estab_assist_saude_fam AS string) AS estabelecimento_saude,
    CAST(nu_estbo_saude AS string) AS id_estabelecimento_saude,
    CAST(nom_centro_assist_fam AS string) AS cras_creas,
    CAST(cod_centro_assist_fam AS string) AS id_cras_creas,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.familia_0609`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS string) AS id_prefeitura,
    CAST(cod_familiar_fam AS string) AS id_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(cod_familia_indigena_fam AS string) AS id_familia_indigena,
    CAST(cod_povo_indigena_fam AS string) AS id_povo_indigena,
    CAST(nom_povo_indigena_fam AS string) AS povo_indigena,
    CAST(vazio2 AS string) AS vazio_2,
    CAST(cod_indigena_reside_fam AS string) AS id_indigena_residente,
    CAST(cod_reserva_indigena_fam AS string) AS id_reserva_indigena,
    CAST(nom_reserva_indigena_fam AS string) AS reserva_indigena,
    CAST(ind_reserva_indigena_fam AS string) AS nao_sabe_reserva_indigena,
    CAST(ind_familia_quilombola_fam AS string) AS familia_quilombola,
    CAST(cod_comunidade_quilombola_fam AS string) AS id_comunidade_quilombola,
    CAST(nom_comunidade_quilombola_fam AS string) AS comunidade_quilombola,
    CAST(ind_comunidade_quilombola_fam AS string) AS nao_sabe_comunidade_quilombola,
    CAST(qtd_pessoas_domic_fam AS int64) AS pessoas_domicilio,
    CAST(qtd_familias_domic_fam AS int64) AS familias_domicilio,
    CAST(qtd_pessoa_inter_0_17_anos_fam AS int64) AS pessoas_internadas_0_17_anos,
    CAST(ind_pessoa_inter_0_17_anos_fam AS string) AS nao_tem_pessoas_internadas_0_17_anos,
    CAST(qtd_pessoa_inter_18_59_anos_fam AS int64) AS pessoas_internadas_18_59_anos,
    CAST(ind_pessoa_inter_18_59_anos_fam AS string) AS nao_tem_pessoas_internadas_18_59_anos,
    CAST(qtd_pessoa_inter_60_anos_fam AS int64) AS pessoas_internadas_mais_60_anos,
    CAST(ind_pessoa_inter_60_anos_fam AS string) AS nao_tem_pessoas_internadas_mais_60_anos,
    CAST(val_desp_energia_fam AS int64) AS despesa_energia,
    CAST(ind_desp_energia_fam AS string) AS nao_tem_despesa_energia,
    CAST(val_desp_agua_esgoto_fam AS int64) AS despesa_agua_esgoto,
    CAST(ind_desp_agua_esgoto_fam AS string) AS nao_tem_despesa_agua_esgoto,
    CAST(val_desp_gas_fam AS int64) AS despesa_gas,
    CAST(ind_desp_gas_fam AS string) AS nao_tem_despesa_gas,
    CAST(val_desp_alimentacao_fam AS int64) AS despesa_alimentacao,
    CAST(ind_desp_alimentacao_fam AS string) AS nao_tem_despesa_alimentacao,
    CAST(val_desp_transpor_fam AS int64) AS despesa_transporte,
    CAST(ind_desp_transpor_fam AS string) AS nao_tem_despesa_transporte,
    CAST(val_desp_aluguel_fam AS int64) AS despesa_aluguel,
    CAST(ind_desp_aluguel_fam AS string) AS nao_tem_despesa_aluguel,
    CAST(val_desp_medicamentos_fam AS int64) AS despesa_medicamentos,
    CAST(ind_desp_medicamentos_fam AS string) AS nao_tem_despesa_medicamentos,
    CAST(nom_estab_assist_saude_fam AS string) AS estabelecimento_saude,
    CAST(nu_estbo_saude AS string) AS id_estabelecimento_saude,
    CAST(nom_centro_assist_fam AS string) AS cras_creas,
    CAST(cod_centro_assist_fam AS string) AS id_cras_creas,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.familia_0612`

