
SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dat_cadastramento_fam) AS DATE) AS data_catrastro,
    CAST(PARSE_DATE('%d%m%Y', dat_alteracao_fam) AS DATE) AS data_alteracao,
    CAST(cod_est_cadastral_fam AS STRING) AS id_estado_cadastro,
    CAST(ind_cadastro_valido_fam AS STRING) AS cadastro_valido,
    CAST(cod_condicao_cadastro_fam AS STRING) AS id_condicao_cadastro,
    CAST(vlr_renda_media_fam AS INT64) AS valor_renda_media,
    CAST(ind_trabalho_infantil_fam AS STRING) AS trabalho_infantil,
    CAST(cod_munic_ibge_2_fam AS STRING) AS id_uf,
    CAST(cod_munic_ibge_5_fam AS STRING) AS id_municipio,
    CAST(cod_ibge_distrito_fam AS STRING) AS id_distrito,
    CAST(cod_ibge_subdistr_fam AS STRING) AS id_subdistrito,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS id_setor_censitario,
    CAST(cod_modalidade_fam AS STRING) AS id_modalidade,
    CAST(cod_forma_coleta_fam AS STRING) AS id_forma_coleta,
    CAST(ind_formulario_0_fam AS STRING) AS formulario_0,
    CAST(ind_formulario_1_fam AS STRING) AS formulario_1,
    CAST(ind_formulario_2_fam AS STRING) AS formulario_2,
    CAST(ind_formulario_sup1_fam AS STRING) AS formulario_suplementar_1,
    CAST(ind_formulario_sup2_fam AS STRING) AS formulario_suplementar_2,
    CAST(dta_entrevista_fam AS STRING) AS data_entrevista,
    CAST(nom_localidade_fam AS STRING) AS localidade,
    CAST(nom_tip_logradouro_fam AS STRING) AS tipo_logradouro,
    CAST(nom_titulo_logradouro_fam AS STRING) AS titulo_logradouro,
    CAST(nom_logradouro_fam AS STRING) AS logradouro,
    CAST(num_logradouro_fam AS STRING) AS numero_logradouro,
    CAST(des_complemento_fam AS STRING) AS complemento,
    CAST(des_complemento_adic_fam AS STRING) AS complemento_adicional,
    CAST(num_cep_logradouro_fam AS STRING) AS cep,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS refencia_logradouro,
    CAST(nom_entrevistador_fam AS STRING) AS entrevistador,
    CAST(num_cpf_entrevistador_fam AS STRING) AS cpf_entrevistador,
    CAST(txt_obs_entrevistador_fam AS STRING) AS observacoes_entrevistador,
    CAST(cod_origem_prefeitura_fam AS STRING) AS id_prefeitura_origem,
    CAST(cod_origem_familia_fam AS STRING) AS id_familia_origem,
    CAST(PARSE_DATE('None', dt_cdstr_atual_fmla) AS DATE) AS data_limite_catastro_atual,
    CAST(flag_fam_alterada_v7 AS STRING) AS alterada_v7,
    CAST(PARSE_DATE('%d%m%Y', dat_atualizacao_familia) AS DATE) AS data_atualizacao,
    CAST(cod_unidade_territorial_fam AS STRING) AS id_unidade_territorial,
    CAST(nom_unidade_territorial_fam AS STRING) AS unidade_territorial,
    CAST(ind_formulario_sup3_fam AS STRING) AS formulario_suplementar_3,
    NULL AS origem_cadastro, --Essa coluna não esta na versao posterior
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.identificacao_controle_0601`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dat_cadastramento_fam) AS DATE) AS data_catrastro,
    CAST(PARSE_DATE('%d%m%Y', dat_alteracao_fam) AS DATE) AS data_alteracao,
    CAST(cod_est_cadastral_fam AS STRING) AS id_estado_cadastro,
    CAST(ind_cadastro_valido_fam AS STRING) AS cadastro_valido,
    CAST(cod_condicao_cadastro_fam AS STRING) AS id_condicao_cadastro,
    CAST(vlr_renda_media_fam AS INT64) AS valor_renda_media,
    CAST(ind_trabalho_infantil_fam AS STRING) AS trabalho_infantil,
    CAST(cod_munic_ibge_2_fam AS STRING) AS id_uf,
    CAST(cod_munic_ibge_5_fam AS STRING) AS id_municipio,
    CAST(cod_ibge_distrito_fam AS STRING) AS id_distrito,
    CAST(cod_ibge_subdistr_fam AS STRING) AS id_subdistrito,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS id_setor_censitario,
    CAST(cod_modalidade_fam AS STRING) AS id_modalidade,
    CAST(cod_forma_coleta_fam AS STRING) AS id_forma_coleta,
    CAST(ind_formulario_0_fam AS STRING) AS formulario_0,
    CAST(ind_formulario_1_fam AS STRING) AS formulario_1,
    CAST(ind_formulario_2_fam AS STRING) AS formulario_2,
    CAST(ind_formulario_sup1_fam AS STRING) AS formulario_suplementar_1,
    CAST(ind_formulario_sup2_fam AS STRING) AS formulario_suplementar_2,
    CAST(dta_entrevista_fam AS STRING) AS data_entrevista,
    CAST(nom_localidade_fam AS STRING) AS localidade,
    CAST(nom_tip_logradouro_fam AS STRING) AS tipo_logradouro,
    CAST(nom_titulo_logradouro_fam AS STRING) AS titulo_logradouro,
    CAST(nom_logradouro_fam AS STRING) AS logradouro,
    CAST(num_logradouro_fam AS STRING) AS numero_logradouro,
    CAST(des_complemento_fam AS STRING) AS complemento,
    CAST(des_complemento_adic_fam AS STRING) AS complemento_adicional,
    CAST(num_cep_logradouro_fam AS STRING) AS cep,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS refencia_logradouro,
    CAST(nom_entrevistador_fam AS STRING) AS entrevistador,
    CAST(num_cpf_entrevistador_fam AS STRING) AS cpf_entrevistador,
    CAST(txt_obs_entrevistador_fam AS STRING) AS observacoes_entrevistador,
    CAST(cod_origem_prefeitura_fam AS STRING) AS id_prefeitura_origem,
    CAST(cod_origem_familia_fam AS STRING) AS id_familia_origem,
    CAST(PARSE_DATE('None', dt_cdstr_atual_fmla) AS DATE) AS data_limite_catastro_atual,
    CAST(flag_fam_alterada_v7 AS STRING) AS alterada_v7,
    CAST(PARSE_DATE('%d%m%Y', dat_atualizacao_familia) AS DATE) AS data_atualizacao,
    CAST(cod_unidade_territorial_fam AS STRING) AS id_unidade_territorial,
    CAST(nom_unidade_territorial_fam AS STRING) AS unidade_territorial,
    CAST(ind_formulario_sup3_fam AS STRING) AS formulario_suplementar_3,
    NULL AS origem_cadastro, --Essa coluna não esta na versao posterior
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.identificacao_controle_0603`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dat_cadastramento_fam) AS DATE) AS data_catrastro,
    CAST(PARSE_DATE('%d%m%Y', dat_alteracao_fam) AS DATE) AS data_alteracao,
    CAST(cod_est_cadastral_fam AS STRING) AS id_estado_cadastro,
    CAST(ind_cadastro_valido_fam AS STRING) AS cadastro_valido,
    CAST(cod_condicao_cadastro_fam AS STRING) AS id_condicao_cadastro,
    CAST(vlr_renda_media_fam AS INT64) AS valor_renda_media,
    CAST(ind_trabalho_infantil_fam AS STRING) AS trabalho_infantil,
    CAST(cod_munic_ibge_2_fam AS STRING) AS id_uf,
    CAST(cod_munic_ibge_5_fam AS STRING) AS id_municipio,
    CAST(cod_ibge_distrito_fam AS STRING) AS id_distrito,
    CAST(cod_ibge_subdistr_fam AS STRING) AS id_subdistrito,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS id_setor_censitario,
    CAST(cod_modalidade_fam AS STRING) AS id_modalidade,
    CAST(cod_forma_coleta_fam AS STRING) AS id_forma_coleta,
    CAST(ind_formulario_0_fam AS STRING) AS formulario_0,
    CAST(ind_formulario_1_fam AS STRING) AS formulario_1,
    CAST(ind_formulario_2_fam AS STRING) AS formulario_2,
    CAST(ind_formulario_sup1_fam AS STRING) AS formulario_suplementar_1,
    CAST(ind_formulario_sup2_fam AS STRING) AS formulario_suplementar_2,
    CAST(dta_entrevista_fam AS STRING) AS data_entrevista,
    CAST(nom_localidade_fam AS STRING) AS localidade,
    CAST(nom_tip_logradouro_fam AS STRING) AS tipo_logradouro,
    CAST(nom_titulo_logradouro_fam AS STRING) AS titulo_logradouro,
    CAST(nom_logradouro_fam AS STRING) AS logradouro,
    CAST(num_logradouro_fam AS STRING) AS numero_logradouro,
    CAST(des_complemento_fam AS STRING) AS complemento,
    CAST(des_complemento_adic_fam AS STRING) AS complemento_adicional,
    CAST(num_cep_logradouro_fam AS STRING) AS cep,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS refencia_logradouro,
    CAST(nom_entrevistador_fam AS STRING) AS entrevistador,
    CAST(num_cpf_entrevistador_fam AS STRING) AS cpf_entrevistador,
    CAST(txt_obs_entrevistador_fam AS STRING) AS observacoes_entrevistador,
    CAST(cod_origem_prefeitura_fam AS STRING) AS id_prefeitura_origem,
    CAST(cod_origem_familia_fam AS STRING) AS id_familia_origem,
    CAST(PARSE_DATE('None', dt_cdstr_atual_fmla) AS DATE) AS data_limite_catastro_atual,
    CAST(flag_fam_alterada_v7 AS STRING) AS alterada_v7,
    CAST(PARSE_DATE('%d%m%Y', dat_atualizacao_familia) AS DATE) AS data_atualizacao,
    CAST(cod_unidade_territorial_fam AS STRING) AS id_unidade_territorial,
    CAST(nom_unidade_territorial_fam AS STRING) AS unidade_territorial,
    CAST(ind_formulario_sup3_fam AS STRING) AS formulario_suplementar_3,
    CAST(nu_origem_cadastro_fam AS STRING) AS origem_cadastro,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.identificacao_controle_0604`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dat_cadastramento_fam) AS DATE) AS data_catrastro,
    CAST(PARSE_DATE('%d%m%Y', dat_alteracao_fam) AS DATE) AS data_alteracao,
    CAST(cod_est_cadastral_fam AS STRING) AS id_estado_cadastro,
    CAST(ind_cadastro_valido_fam AS STRING) AS cadastro_valido,
    CAST(cod_condicao_cadastro_fam AS STRING) AS id_condicao_cadastro,
    CAST(vlr_renda_media_fam AS INT64) AS valor_renda_media,
    CAST(ind_trabalho_infantil_fam AS STRING) AS trabalho_infantil,
    CAST(cod_munic_ibge_2_fam AS STRING) AS id_uf,
    CAST(cod_munic_ibge_5_fam AS STRING) AS id_municipio,
    CAST(cod_ibge_distrito_fam AS STRING) AS id_distrito,
    CAST(cod_ibge_subdistr_fam AS STRING) AS id_subdistrito,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS id_setor_censitario,
    CAST(cod_modalidade_fam AS STRING) AS id_modalidade,
    CAST(cod_forma_coleta_fam AS STRING) AS id_forma_coleta,
    CAST(ind_formulario_0_fam AS STRING) AS formulario_0,
    CAST(ind_formulario_1_fam AS STRING) AS formulario_1,
    CAST(ind_formulario_2_fam AS STRING) AS formulario_2,
    CAST(ind_formulario_sup1_fam AS STRING) AS formulario_suplementar_1,
    CAST(ind_formulario_sup2_fam AS STRING) AS formulario_suplementar_2,
    CAST(dta_entrevista_fam AS STRING) AS data_entrevista,
    CAST(nom_localidade_fam AS STRING) AS localidade,
    CAST(nom_tip_logradouro_fam AS STRING) AS tipo_logradouro,
    CAST(nom_titulo_logradouro_fam AS STRING) AS titulo_logradouro,
    CAST(nom_logradouro_fam AS STRING) AS logradouro,
    CAST(num_logradouro_fam AS STRING) AS numero_logradouro,
    CAST(des_complemento_fam AS STRING) AS complemento,
    CAST(des_complemento_adic_fam AS STRING) AS complemento_adicional,
    CAST(num_cep_logradouro_fam AS STRING) AS cep,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS refencia_logradouro,
    CAST(nom_entrevistador_fam AS STRING) AS entrevistador,
    CAST(num_cpf_entrevistador_fam AS STRING) AS cpf_entrevistador,
    CAST(txt_obs_entrevistador_fam AS STRING) AS observacoes_entrevistador,
    CAST(cod_origem_prefeitura_fam AS STRING) AS id_prefeitura_origem,
    CAST(cod_origem_familia_fam AS STRING) AS id_familia_origem,
    CAST(PARSE_DATE('None', dt_cdstr_atual_fmla) AS DATE) AS data_limite_catastro_atual,
    CAST(flag_fam_alterada_v7 AS STRING) AS alterada_v7,
    CAST(PARSE_DATE('%d%m%Y', dat_atualizacao_familia) AS DATE) AS data_atualizacao,
    CAST(cod_unidade_territorial_fam AS STRING) AS id_unidade_territorial,
    CAST(nom_unidade_territorial_fam AS STRING) AS unidade_territorial,
    CAST(ind_formulario_sup3_fam AS STRING) AS formulario_suplementar_3,
    CAST(nu_origem_cadastro_fam AS STRING) AS origem_cadastro,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.identificacao_controle_0609`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS id_prefeitura,
    CAST(cod_familiar_fam AS STRING) AS id_familia,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dat_cadastramento_fam) AS DATE) AS data_catrastro,
    CAST(PARSE_DATE('%d%m%Y', dat_alteracao_fam) AS DATE) AS data_alteracao,
    CAST(cod_est_cadastral_fam AS STRING) AS id_estado_cadastro,
    CAST(ind_cadastro_valido_fam AS STRING) AS cadastro_valido,
    CAST(cod_condicao_cadastro_fam AS STRING) AS id_condicao_cadastro,
    CAST(vlr_renda_media_fam AS INT64) AS valor_renda_media,
    CAST(ind_trabalho_infantil_fam AS STRING) AS trabalho_infantil,
    CAST(cod_munic_ibge_2_fam AS STRING) AS id_uf,
    CAST(cod_munic_ibge_5_fam AS STRING) AS id_municipio,
    CAST(cod_ibge_distrito_fam AS STRING) AS id_distrito,
    CAST(cod_ibge_subdistr_fam AS STRING) AS id_subdistrito,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS id_setor_censitario,
    CAST(cod_modalidade_fam AS STRING) AS id_modalidade,
    CAST(cod_forma_coleta_fam AS STRING) AS id_forma_coleta,
    CAST(ind_formulario_0_fam AS STRING) AS formulario_0,
    CAST(ind_formulario_1_fam AS STRING) AS formulario_1,
    CAST(ind_formulario_2_fam AS STRING) AS formulario_2,
    CAST(ind_formulario_sup1_fam AS STRING) AS formulario_suplementar_1,
    CAST(ind_formulario_sup2_fam AS STRING) AS formulario_suplementar_2,
    CAST(dta_entrevista_fam AS STRING) AS data_entrevista,
    CAST(nom_localidade_fam AS STRING) AS localidade,
    CAST(nom_tip_logradouro_fam AS STRING) AS tipo_logradouro,
    CAST(nom_titulo_logradouro_fam AS STRING) AS titulo_logradouro,
    CAST(nom_logradouro_fam AS STRING) AS logradouro,
    CAST(num_logradouro_fam AS STRING) AS numero_logradouro,
    CAST(des_complemento_fam AS STRING) AS complemento,
    CAST(des_complemento_adic_fam AS STRING) AS complemento_adicional,
    CAST(num_cep_logradouro_fam AS STRING) AS cep,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS refencia_logradouro,
    CAST(nom_entrevistador_fam AS STRING) AS entrevistador,
    CAST(num_cpf_entrevistador_fam AS STRING) AS cpf_entrevistador,
    CAST(txt_obs_entrevistador_fam AS STRING) AS observacoes_entrevistador,
    CAST(cod_origem_prefeitura_fam AS STRING) AS id_prefeitura_origem,
    CAST(cod_origem_familia_fam AS STRING) AS id_familia_origem,
    CAST(PARSE_DATE('None', dt_cdstr_atual_fmla) AS DATE) AS data_limite_catastro_atual,
    CAST(flag_fam_alterada_v7 AS STRING) AS alterada_v7,
    CAST(PARSE_DATE('%d%m%Y', dat_atualizacao_familia) AS DATE) AS data_atualizacao,
    CAST(cod_unidade_territorial_fam AS STRING) AS id_unidade_territorial,
    CAST(nom_unidade_territorial_fam AS STRING) AS unidade_territorial,
    CAST(ind_formulario_sup3_fam AS STRING) AS formulario_suplementar_3,
    CAST(nu_origem_cadastro_fam AS STRING) AS origem_cadastro,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.identificacao_controle_0612`

