
SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS STRING) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS STRING) AS id_interno_representante_legal,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dta_cadastramento_rl) AS DATE) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS STRING) AS representante_legal,
    CAST(num_nis_pessoa_rl AS STRING) AS nis_representante_legal,
    CAST(cod_sexo_rl AS STRING) AS id_sexo_representante_legal,
    CAST(PARSE_DATE('%d%m%Y', dta_nasc_rl) AS DATE) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS STRING) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS STRING) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS STRING) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS STRING) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS STRING) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS STRING) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS STRING) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS STRING) AS cpf_representante_legal,
    CAST(ic_obito_rl AS STRING) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS STRING) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS STRING) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS STRING) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS STRING) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS STRING) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS STRING) AS email_representante_legal,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS STRING) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS STRING) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS STRING) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS STRING) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS STRING) AS cep_representante_legal,
    CAST(nome_bairro_rl AS STRING) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS STRING) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS STRING) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.representante_legal_0601`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS STRING) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS STRING) AS id_interno_representante_legal,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dta_cadastramento_rl) AS DATE) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS STRING) AS representante_legal,
    CAST(num_nis_pessoa_rl AS STRING) AS nis_representante_legal,
    CAST(cod_sexo_rl AS STRING) AS id_sexo_representante_legal,
    CAST(PARSE_DATE('%d%m%Y', dta_nasc_rl) AS DATE) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS STRING) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS STRING) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS STRING) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS STRING) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS STRING) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS STRING) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS STRING) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS STRING) AS cpf_representante_legal,
    CAST(ic_obito_rl AS STRING) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS STRING) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS STRING) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS STRING) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS STRING) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS STRING) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS STRING) AS email_representante_legal,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS STRING) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS STRING) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS STRING) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS STRING) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS STRING) AS cep_representante_legal,
    CAST(nome_bairro_rl AS STRING) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS STRING) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS STRING) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.representante_legal_0603`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS STRING) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS STRING) AS id_interno_representante_legal,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dta_cadastramento_rl) AS DATE) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS STRING) AS representante_legal,
    CAST(num_nis_pessoa_rl AS STRING) AS nis_representante_legal,
    CAST(cod_sexo_rl AS STRING) AS id_sexo_representante_legal,
    CAST(PARSE_DATE('%d%m%Y', dta_nasc_rl) AS DATE) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS STRING) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS STRING) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS STRING) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS STRING) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS STRING) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS STRING) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS STRING) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS STRING) AS cpf_representante_legal,
    CAST(ic_obito_rl AS STRING) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS STRING) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS STRING) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS STRING) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS STRING) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS STRING) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS STRING) AS email_representante_legal,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS STRING) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS STRING) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS STRING) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS STRING) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS STRING) AS cep_representante_legal,
    CAST(nome_bairro_rl AS STRING) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS STRING) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS STRING) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.representante_legal_0604`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS STRING) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS STRING) AS id_interno_representante_legal,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dta_cadastramento_rl) AS DATE) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS STRING) AS representante_legal,
    CAST(num_nis_pessoa_rl AS STRING) AS nis_representante_legal,
    CAST(cod_sexo_rl AS STRING) AS id_sexo_representante_legal,
    CAST(PARSE_DATE('%d%m%Y', dta_nasc_rl) AS DATE) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS STRING) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS STRING) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS STRING) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS STRING) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS STRING) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS STRING) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS STRING) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS STRING) AS cpf_representante_legal,
    CAST(ic_obito_rl AS STRING) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS STRING) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS STRING) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS STRING) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS STRING) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS STRING) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS STRING) AS email_representante_legal,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS STRING) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS STRING) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS STRING) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS STRING) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS STRING) AS cep_representante_legal,
    CAST(nome_bairro_rl AS STRING) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS STRING) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS STRING) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.representante_legal_0609`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS STRING) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS STRING) AS id_interno_representante_legal,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS numero_registro_arquivo,
    CAST(PARSE_DATE('%d%m%Y', dta_cadastramento_rl) AS DATE) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS STRING) AS representante_legal,
    CAST(num_nis_pessoa_rl AS STRING) AS nis_representante_legal,
    CAST(cod_sexo_rl AS STRING) AS id_sexo_representante_legal,
    CAST(PARSE_DATE('%d%m%Y', dta_nasc_rl) AS DATE) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS STRING) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS STRING) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS STRING) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS STRING) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS STRING) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS STRING) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS STRING) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS STRING) AS cpf_representante_legal,
    CAST(ic_obito_rl AS STRING) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS STRING) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS STRING) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS STRING) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS STRING) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS STRING) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS STRING) AS email_representante_legal,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS STRING) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS STRING) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS STRING) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS STRING) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS STRING) AS cep_representante_legal,
    CAST(nome_bairro_rl AS STRING) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS STRING) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS STRING) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_versao.representante_legal_0612`

