
SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dat_cadastramento_fam AS STRING) AS dat_cadastramento_fam,
    CAST(dat_alteracao_fam AS STRING) AS dat_alteracao_fam,
    CAST(cod_est_cadastral_fam AS STRING) AS cod_est_cadastral_fam,
    CAST(ind_cadastro_valido_fam AS STRING) AS ind_cadastro_valido_fam,
    CAST(cod_condicao_cadastro_fam AS STRING) AS cod_condicao_cadastro_fam,
    CAST(vlr_renda_media_fam AS STRING) AS vlr_renda_media_fam,
    CAST(ind_trabalho_infantil_fam AS STRING) AS ind_trabalho_infantil_fam,
    CAST(cod_munic_ibge_2_fam AS STRING) AS cod_munic_ibge_2_fam,
    CAST(cod_munic_ibge_5_fam AS STRING) AS cod_munic_ibge_5_fam,
    CAST(cod_ibge_distrito_fam AS STRING) AS cod_ibge_distrito_fam,
    CAST(cod_ibge_subdistr_fam AS STRING) AS cod_ibge_subdistr_fam,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS cod_ibge_setor_censo_fam,
    CAST(cod_modalidade_fam AS STRING) AS cod_modalidade_fam,
    CAST(cod_forma_coleta_fam AS STRING) AS cod_forma_coleta_fam,
    CAST(ind_formulario_0_fam AS STRING) AS ind_formulario_0_fam,
    CAST(ind_formulario_1_fam AS STRING) AS ind_formulario_1_fam,
    CAST(ind_formulario_2_fam AS STRING) AS ind_formulario_2_fam,
    CAST(ind_formulario_sup1_fam AS STRING) AS ind_formulario_sup1_fam,
    CAST(ind_formulario_sup2_fam AS STRING) AS ind_formulario_sup2_fam,
    CAST(dta_entrevista_fam AS STRING) AS dta_entrevista_fam,
    CAST(nom_localidade_fam AS STRING) AS nom_localidade_fam,
    CAST(nom_tip_logradouro_fam AS STRING) AS nom_tip_logradouro_fam,
    CAST(nom_titulo_logradouro_fam AS STRING) AS nom_titulo_logradouro_fam,
    CAST(nom_logradouro_fam AS STRING) AS nom_logradouro_fam,
    CAST(num_logradouro_fam AS STRING) AS num_logradouro_fam,
    CAST(des_complemento_fam AS STRING) AS des_complemento_fam,
    CAST(des_complemento_adic_fam AS STRING) AS des_complemento_adic_fam,
    CAST(num_cep_logradouro_fam AS STRING) AS num_cep_logradouro_fam,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS txt_referencia_local_fam,
    CAST(nom_entrevistador_fam AS STRING) AS nom_entrevistador_fam,
    CAST(num_cpf_entrevistador_fam AS STRING) AS num_cpf_entrevistador_fam,
    CAST(txt_obs_entrevistador_fam AS STRING) AS txt_obs_entrevistador_fam,
    CAST(cod_origem_prefeitura_fam AS STRING) AS cod_origem_prefeitura_fam,
    CAST(cod_origem_familia_fam AS STRING) AS cod_origem_familia_fam,
    CAST(dt_cdstr_atual_fmla AS STRING) AS dt_cdstr_atual_fmla,
    CAST(flag_fam_alterada_v7 AS STRING) AS flag_fam_alterada_v7,
    CAST(dat_atualizacao_familia AS STRING) AS dat_atualizacao_familia,
    CAST(cod_unidade_territorial_fam AS STRING) AS cod_unidade_territorial_fam,
    CAST(nom_unidade_territorial_fam AS STRING) AS nom_unidade_territorial_fam,
    CAST(ind_formulario_sup3_fam AS STRING) AS ind_formulario_sup3_fam,
    NULL AS nu_origem_cadastro_fam, --Essa coluna não esta na versao posterior
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.01_0601_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dat_cadastramento_fam AS STRING) AS dat_cadastramento_fam,
    CAST(dat_alteracao_fam AS STRING) AS dat_alteracao_fam,
    CAST(cod_est_cadastral_fam AS STRING) AS cod_est_cadastral_fam,
    CAST(ind_cadastro_valido_fam AS STRING) AS ind_cadastro_valido_fam,
    CAST(cod_condicao_cadastro_fam AS STRING) AS cod_condicao_cadastro_fam,
    CAST(vlr_renda_media_fam AS STRING) AS vlr_renda_media_fam,
    CAST(ind_trabalho_infantil_fam AS STRING) AS ind_trabalho_infantil_fam,
    CAST(cod_munic_ibge_2_fam AS STRING) AS cod_munic_ibge_2_fam,
    CAST(cod_munic_ibge_5_fam AS STRING) AS cod_munic_ibge_5_fam,
    CAST(cod_ibge_distrito_fam AS STRING) AS cod_ibge_distrito_fam,
    CAST(cod_ibge_subdistr_fam AS STRING) AS cod_ibge_subdistr_fam,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS cod_ibge_setor_censo_fam,
    CAST(cod_modalidade_fam AS STRING) AS cod_modalidade_fam,
    CAST(cod_forma_coleta_fam AS STRING) AS cod_forma_coleta_fam,
    CAST(ind_formulario_0_fam AS STRING) AS ind_formulario_0_fam,
    CAST(ind_formulario_1_fam AS STRING) AS ind_formulario_1_fam,
    CAST(ind_formulario_2_fam AS STRING) AS ind_formulario_2_fam,
    CAST(ind_formulario_sup1_fam AS STRING) AS ind_formulario_sup1_fam,
    CAST(ind_formulario_sup2_fam AS STRING) AS ind_formulario_sup2_fam,
    CAST(dta_entrevista_fam AS STRING) AS dta_entrevista_fam,
    CAST(nom_localidade_fam AS STRING) AS nom_localidade_fam,
    CAST(nom_tip_logradouro_fam AS STRING) AS nom_tip_logradouro_fam,
    CAST(nom_titulo_logradouro_fam AS STRING) AS nom_titulo_logradouro_fam,
    CAST(nom_logradouro_fam AS STRING) AS nom_logradouro_fam,
    CAST(num_logradouro_fam AS STRING) AS num_logradouro_fam,
    CAST(des_complemento_fam AS STRING) AS des_complemento_fam,
    CAST(des_complemento_adic_fam AS STRING) AS des_complemento_adic_fam,
    CAST(num_cep_logradouro_fam AS STRING) AS num_cep_logradouro_fam,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS txt_referencia_local_fam,
    CAST(nom_entrevistador_fam AS STRING) AS nom_entrevistador_fam,
    CAST(num_cpf_entrevistador_fam AS STRING) AS num_cpf_entrevistador_fam,
    CAST(txt_obs_entrevistador_fam AS STRING) AS txt_obs_entrevistador_fam,
    CAST(cod_origem_prefeitura_fam AS STRING) AS cod_origem_prefeitura_fam,
    CAST(cod_origem_familia_fam AS STRING) AS cod_origem_familia_fam,
    CAST(dt_cdstr_atual_fmla AS STRING) AS dt_cdstr_atual_fmla,
    CAST(flag_fam_alterada_v7 AS STRING) AS flag_fam_alterada_v7,
    CAST(dat_atualizacao_familia AS STRING) AS dat_atualizacao_familia,
    CAST(cod_unidade_territorial_fam AS STRING) AS cod_unidade_territorial_fam,
    CAST(nom_unidade_territorial_fam AS STRING) AS nom_unidade_territorial_fam,
    CAST(ind_formulario_sup3_fam AS STRING) AS ind_formulario_sup3_fam,
    NULL AS nu_origem_cadastro_fam, --Essa coluna não esta na versao posterior
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.01_0604_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dat_cadastramento_fam AS STRING) AS dat_cadastramento_fam,
    CAST(dat_alteracao_fam AS STRING) AS dat_alteracao_fam,
    CAST(cod_est_cadastral_fam AS STRING) AS cod_est_cadastral_fam,
    CAST(ind_cadastro_valido_fam AS STRING) AS ind_cadastro_valido_fam,
    CAST(cod_condicao_cadastro_fam AS STRING) AS cod_condicao_cadastro_fam,
    CAST(vlr_renda_media_fam AS STRING) AS vlr_renda_media_fam,
    CAST(ind_trabalho_infantil_fam AS STRING) AS ind_trabalho_infantil_fam,
    CAST(cod_munic_ibge_2_fam AS STRING) AS cod_munic_ibge_2_fam,
    CAST(cod_munic_ibge_5_fam AS STRING) AS cod_munic_ibge_5_fam,
    CAST(cod_ibge_distrito_fam AS STRING) AS cod_ibge_distrito_fam,
    CAST(cod_ibge_subdistr_fam AS STRING) AS cod_ibge_subdistr_fam,
    CAST(cod_ibge_setor_censo_fam AS STRING) AS cod_ibge_setor_censo_fam,
    CAST(cod_modalidade_fam AS STRING) AS cod_modalidade_fam,
    CAST(cod_forma_coleta_fam AS STRING) AS cod_forma_coleta_fam,
    CAST(ind_formulario_0_fam AS STRING) AS ind_formulario_0_fam,
    CAST(ind_formulario_1_fam AS STRING) AS ind_formulario_1_fam,
    CAST(ind_formulario_2_fam AS STRING) AS ind_formulario_2_fam,
    CAST(ind_formulario_sup1_fam AS STRING) AS ind_formulario_sup1_fam,
    CAST(ind_formulario_sup2_fam AS STRING) AS ind_formulario_sup2_fam,
    CAST(dta_entrevista_fam AS STRING) AS dta_entrevista_fam,
    CAST(nom_localidade_fam AS STRING) AS nom_localidade_fam,
    CAST(nom_tip_logradouro_fam AS STRING) AS nom_tip_logradouro_fam,
    CAST(nom_titulo_logradouro_fam AS STRING) AS nom_titulo_logradouro_fam,
    CAST(nom_logradouro_fam AS STRING) AS nom_logradouro_fam,
    CAST(num_logradouro_fam AS STRING) AS num_logradouro_fam,
    CAST(des_complemento_fam AS STRING) AS des_complemento_fam,
    CAST(des_complemento_adic_fam AS STRING) AS des_complemento_adic_fam,
    CAST(num_cep_logradouro_fam AS STRING) AS num_cep_logradouro_fam,
    CAST(filler AS STRING) AS filler,
    CAST(txt_referencia_local_fam AS STRING) AS txt_referencia_local_fam,
    CAST(nom_entrevistador_fam AS STRING) AS nom_entrevistador_fam,
    CAST(num_cpf_entrevistador_fam AS STRING) AS num_cpf_entrevistador_fam,
    CAST(txt_obs_entrevistador_fam AS STRING) AS txt_obs_entrevistador_fam,
    CAST(cod_origem_prefeitura_fam AS STRING) AS cod_origem_prefeitura_fam,
    CAST(cod_origem_familia_fam AS STRING) AS cod_origem_familia_fam,
    CAST(dt_cdstr_atual_fmla AS STRING) AS dt_cdstr_atual_fmla,
    CAST(flag_fam_alterada_v7 AS STRING) AS flag_fam_alterada_v7,
    CAST(dat_atualizacao_familia AS STRING) AS dat_atualizacao_familia,
    CAST(cod_unidade_territorial_fam AS STRING) AS cod_unidade_territorial_fam,
    CAST(nom_unidade_territorial_fam AS STRING) AS nom_unidade_territorial_fam,
    CAST(ind_formulario_sup3_fam AS STRING) AS ind_formulario_sup3_fam,
    CAST(nu_origem_cadastro_fam AS STRING) AS nu_origem_cadastro_fam,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.01_0609_test`

