
SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_cadastramento_memb AS STRING) AS dta_cadastramento_memb,
    CAST(dta_atual_memb AS STRING) AS dta_atual_memb,
    CAST(cod_est_cadastral_memb AS STRING) AS cod_est_cadastral_memb,
    CAST(ind_trabalho_infantil_pessoa AS STRING) AS ind_trabalho_infantil_pessoa,
    CAST(num_ordem_pessoa AS STRING) AS num_ordem_pessoa,
    CAST(nom_pessoa AS STRING) AS nom_pessoa,
    CAST(num_nis_pessoa_atual AS STRING) AS num_nis_pessoa_atual,
    CAST(nom_apelido_pessoa AS STRING) AS nom_apelido_pessoa,
    CAST(cod_sexo_pessoa AS STRING) AS cod_sexo_pessoa,
    CAST(dta_nasc_pessoa AS STRING) AS dta_nasc_pessoa,
    CAST(cod_parentesco_rf_pessoa AS STRING) AS cod_parentesco_rf_pessoa,
    CAST(cod_raca_cor_pessoa AS STRING) AS cod_raca_cor_pessoa,
    CAST(nom_completo_mae_pessoa AS STRING) AS nom_completo_mae_pessoa,
    CAST(ind_nom_completo_mae_pessoa AS STRING) AS ind_nom_completo_mae_pessoa,
    CAST(nom_completo_pai_pessoa AS STRING) AS nom_completo_pai_pessoa,
    CAST(ind_nom_completo_pai_pessoa AS STRING) AS ind_nom_completo_pai_pessoa,
    CAST(cod_local_nascimento_pessoa AS STRING) AS cod_local_nascimento_pessoa,
    CAST(sig_uf_munic_nasc_pessoa AS STRING) AS sig_uf_munic_nasc_pessoa,
    CAST(ind_uf_munic_nasc_pessoa AS STRING) AS ind_uf_munic_nasc_pessoa,
    CAST(nom_ibge_munic_nasc_pessoa AS STRING) AS nom_ibge_munic_nasc_pessoa,
    CAST(cod_ibge_munic_nasc_pessoa AS STRING) AS cod_ibge_munic_nasc_pessoa,
    CAST(ind_ibge_munic_nasc_pessoa AS STRING) AS ind_ibge_munic_nasc_pessoa,
    CAST(nom_pais_origem_pessoa AS STRING) AS nom_pais_origem_pessoa,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(ind_pais_origem_pessoa AS STRING) AS ind_pais_origem_pessoa,
    CAST(cod_certidao_registrada_pessoa AS STRING) AS cod_certidao_registrada_pessoa,
    CAST(cod_origem_prefeitura_pessoa AS STRING) AS cod_origem_prefeitura_pessoa,
    CAST(cod_origem_familia_pessoa AS STRING) AS cod_origem_familia_pessoa,
    CAST(ind_transferencia_pessoa AS STRING) AS ind_transferencia_pessoa,
    CAST(nom_origem_alteracao_pessoa AS STRING) AS nom_origem_alteracao_pessoa,
    CAST(chv_nat_pes_atual AS STRING) AS chv_nat_pes_atual,
    CAST(chv_nat_pes_original AS STRING) AS chv_nat_pes_original,
    CAST(nu_nis_original AS STRING) AS nu_nis_original,
    CAST(cod_pais_origem_pessoa AS STRING) AS cod_pais_origem_pessoa,
    NULL AS nu_origem_cadastro_pessoa, --##Essa coluna não esta na versao posterior
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.04_0601_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_cadastramento_memb AS STRING) AS dta_cadastramento_memb,
    CAST(dta_atual_memb AS STRING) AS dta_atual_memb,
    CAST(cod_est_cadastral_memb AS STRING) AS cod_est_cadastral_memb,
    CAST(ind_trabalho_infantil_pessoa AS STRING) AS ind_trabalho_infantil_pessoa,
    CAST(num_ordem_pessoa AS STRING) AS num_ordem_pessoa,
    CAST(nom_pessoa AS STRING) AS nom_pessoa,
    CAST(num_nis_pessoa_atual AS STRING) AS num_nis_pessoa_atual,
    CAST(nom_apelido_pessoa AS STRING) AS nom_apelido_pessoa,
    CAST(cod_sexo_pessoa AS STRING) AS cod_sexo_pessoa,
    CAST(dta_nasc_pessoa AS STRING) AS dta_nasc_pessoa,
    CAST(cod_parentesco_rf_pessoa AS STRING) AS cod_parentesco_rf_pessoa,
    CAST(cod_raca_cor_pessoa AS STRING) AS cod_raca_cor_pessoa,
    CAST(nom_completo_mae_pessoa AS STRING) AS nom_completo_mae_pessoa,
    CAST(ind_nom_completo_mae_pessoa AS STRING) AS ind_nom_completo_mae_pessoa,
    CAST(nom_completo_pai_pessoa AS STRING) AS nom_completo_pai_pessoa,
    CAST(ind_nom_completo_pai_pessoa AS STRING) AS ind_nom_completo_pai_pessoa,
    CAST(cod_local_nascimento_pessoa AS STRING) AS cod_local_nascimento_pessoa,
    CAST(sig_uf_munic_nasc_pessoa AS STRING) AS sig_uf_munic_nasc_pessoa,
    CAST(ind_uf_munic_nasc_pessoa AS STRING) AS ind_uf_munic_nasc_pessoa,
    CAST(nom_ibge_munic_nasc_pessoa AS STRING) AS nom_ibge_munic_nasc_pessoa,
    CAST(cod_ibge_munic_nasc_pessoa AS STRING) AS cod_ibge_munic_nasc_pessoa,
    CAST(ind_ibge_munic_nasc_pessoa AS STRING) AS ind_ibge_munic_nasc_pessoa,
    CAST(nom_pais_origem_pessoa AS STRING) AS nom_pais_origem_pessoa,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(ind_pais_origem_pessoa AS STRING) AS ind_pais_origem_pessoa,
    CAST(cod_certidao_registrada_pessoa AS STRING) AS cod_certidao_registrada_pessoa,
    CAST(cod_origem_prefeitura_pessoa AS STRING) AS cod_origem_prefeitura_pessoa,
    CAST(cod_origem_familia_pessoa AS STRING) AS cod_origem_familia_pessoa,
    CAST(ind_transferencia_pessoa AS STRING) AS ind_transferencia_pessoa,
    CAST(nom_origem_alteracao_pessoa AS STRING) AS nom_origem_alteracao_pessoa,
    CAST(chv_nat_pes_atual AS STRING) AS chv_nat_pes_atual,
    CAST(chv_nat_pes_original AS STRING) AS chv_nat_pes_original,
    CAST(nu_nis_original AS STRING) AS nu_nis_original,
    CAST(cod_pais_origem_pessoa AS STRING) AS cod_pais_origem_pessoa,
    NULL AS nu_origem_cadastro_pessoa, --##Essa coluna não esta na versao posterior
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.04_0604_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_cadastramento_memb AS STRING) AS dta_cadastramento_memb,
    CAST(dta_atual_memb AS STRING) AS dta_atual_memb,
    CAST(cod_est_cadastral_memb AS STRING) AS cod_est_cadastral_memb,
    CAST(ind_trabalho_infantil_pessoa AS STRING) AS ind_trabalho_infantil_pessoa,
    CAST(num_ordem_pessoa AS STRING) AS num_ordem_pessoa,
    CAST(nom_pessoa AS STRING) AS nom_pessoa,
    CAST(num_nis_pessoa_atual AS STRING) AS num_nis_pessoa_atual,
    CAST(nom_apelido_pessoa AS STRING) AS nom_apelido_pessoa,
    CAST(cod_sexo_pessoa AS STRING) AS cod_sexo_pessoa,
    CAST(dta_nasc_pessoa AS STRING) AS dta_nasc_pessoa,
    CAST(cod_parentesco_rf_pessoa AS STRING) AS cod_parentesco_rf_pessoa,
    CAST(cod_raca_cor_pessoa AS STRING) AS cod_raca_cor_pessoa,
    CAST(nom_completo_mae_pessoa AS STRING) AS nom_completo_mae_pessoa,
    CAST(ind_nom_completo_mae_pessoa AS STRING) AS ind_nom_completo_mae_pessoa,
    CAST(nom_completo_pai_pessoa AS STRING) AS nom_completo_pai_pessoa,
    CAST(ind_nom_completo_pai_pessoa AS STRING) AS ind_nom_completo_pai_pessoa,
    CAST(cod_local_nascimento_pessoa AS STRING) AS cod_local_nascimento_pessoa,
    CAST(sig_uf_munic_nasc_pessoa AS STRING) AS sig_uf_munic_nasc_pessoa,
    CAST(ind_uf_munic_nasc_pessoa AS STRING) AS ind_uf_munic_nasc_pessoa,
    CAST(nom_ibge_munic_nasc_pessoa AS STRING) AS nom_ibge_munic_nasc_pessoa,
    CAST(cod_ibge_munic_nasc_pessoa AS STRING) AS cod_ibge_munic_nasc_pessoa,
    CAST(ind_ibge_munic_nasc_pessoa AS STRING) AS ind_ibge_munic_nasc_pessoa,
    CAST(nom_pais_origem_pessoa AS STRING) AS nom_pais_origem_pessoa,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(ind_pais_origem_pessoa AS STRING) AS ind_pais_origem_pessoa,
    CAST(cod_certidao_registrada_pessoa AS STRING) AS cod_certidao_registrada_pessoa,
    CAST(cod_origem_prefeitura_pessoa AS STRING) AS cod_origem_prefeitura_pessoa,
    CAST(cod_origem_familia_pessoa AS STRING) AS cod_origem_familia_pessoa,
    CAST(ind_transferencia_pessoa AS STRING) AS ind_transferencia_pessoa,
    CAST(nom_origem_alteracao_pessoa AS STRING) AS nom_origem_alteracao_pessoa,
    CAST(chv_nat_pes_atual AS STRING) AS chv_nat_pes_atual,
    CAST(chv_nat_pes_original AS STRING) AS chv_nat_pes_original,
    CAST(nu_nis_original AS STRING) AS nu_nis_original,
    CAST(cod_pais_origem_pessoa AS STRING) AS cod_pais_origem_pessoa,
    CAST(nu_origem_cadastro_pessoa AS STRING) AS nu_origem_cadastro_pessoa,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.04_0609_test`

