
SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_certidao_civil_pessoa AS STRING) AS cod_certidao_civil_pessoa,
    CAST(nom_cartorio_pessoa AS STRING) AS nom_cartorio_pessoa,
    CAST(cod_livro_termo_certid_pessoa AS STRING) AS cod_livro_termo_certid_pessoa,
    CAST(cod_folha_termo_certid_pessoa AS STRING) AS cod_folha_termo_certid_pessoa,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(dta_emissao_certid_pessoa AS STRING) AS dta_emissao_certid_pessoa,
    CAST(sig_uf_certid_pessoa AS STRING) AS sig_uf_certid_pessoa,
    CAST(nom_munic_certid_pessoa AS STRING) AS nom_munic_certid_pessoa,
    CAST(cod_ibge_munic_certid_pessoa AS STRING) AS cod_ibge_munic_certid_pessoa,
    CAST(cod_cartorio_certid_pessoa AS STRING) AS cod_cartorio_certid_pessoa,
    CAST(num_cpf_pessoa AS STRING) AS num_cpf_pessoa,
    CAST(vazio_3 AS STRING) AS vazio_3,
    CAST(cod_complemento_pessoa AS STRING) AS cod_complemento_pessoa,
    CAST(dta_emissao_ident_pessoa AS STRING) AS dta_emissao_ident_pessoa,
    CAST(sig_uf_ident_pessoa AS STRING) AS sig_uf_ident_pessoa,
    CAST(sig_orgao_emissor_pessoa AS STRING) AS sig_orgao_emissor_pessoa,
    CAST(num_cart_trab_prev_soc_pessoa AS STRING) AS num_cart_trab_prev_soc_pessoa,
    CAST(num_serie_trab_prev_soc_pessoa AS STRING) AS num_serie_trab_prev_soc_pessoa,
    CAST(dta_emissao_cart_trab_pessoa AS STRING) AS dta_emissao_cart_trab_pessoa,
    CAST(sig_uf_cart_trab_pessoa AS STRING) AS sig_uf_cart_trab_pessoa,
    CAST(num_titulo_eleitor_pessoa AS STRING) AS num_titulo_eleitor_pessoa,
    CAST(num_zona_tit_eleitor_pessoa AS STRING) AS num_zona_tit_eleitor_pessoa,
    CAST(num_secao_tit_eleitor_pessoa AS STRING) AS num_secao_tit_eleitor_pessoa,
    CAST(cod_termo___matricula__certid_pessoa AS STRING) AS cod_termo___matricula__certid_pessoa,
    CAST(num_identidade_pessoa AS STRING) AS num_identidade_pessoa,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.05_0601_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_certidao_civil_pessoa AS STRING) AS cod_certidao_civil_pessoa,
    CAST(nom_cartorio_pessoa AS STRING) AS nom_cartorio_pessoa,
    CAST(cod_livro_termo_certid_pessoa AS STRING) AS cod_livro_termo_certid_pessoa,
    CAST(cod_folha_termo_certid_pessoa AS STRING) AS cod_folha_termo_certid_pessoa,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(dta_emissao_certid_pessoa AS STRING) AS dta_emissao_certid_pessoa,
    CAST(sig_uf_certid_pessoa AS STRING) AS sig_uf_certid_pessoa,
    CAST(nom_munic_certid_pessoa AS STRING) AS nom_munic_certid_pessoa,
    CAST(cod_ibge_munic_certid_pessoa AS STRING) AS cod_ibge_munic_certid_pessoa,
    CAST(cod_cartorio_certid_pessoa AS STRING) AS cod_cartorio_certid_pessoa,
    CAST(num_cpf_pessoa AS STRING) AS num_cpf_pessoa,
    CAST(vazio_3 AS STRING) AS vazio_3,
    CAST(cod_complemento_pessoa AS STRING) AS cod_complemento_pessoa,
    CAST(dta_emissao_ident_pessoa AS STRING) AS dta_emissao_ident_pessoa,
    CAST(sig_uf_ident_pessoa AS STRING) AS sig_uf_ident_pessoa,
    CAST(sig_orgao_emissor_pessoa AS STRING) AS sig_orgao_emissor_pessoa,
    CAST(num_cart_trab_prev_soc_pessoa AS STRING) AS num_cart_trab_prev_soc_pessoa,
    CAST(num_serie_trab_prev_soc_pessoa AS STRING) AS num_serie_trab_prev_soc_pessoa,
    CAST(dta_emissao_cart_trab_pessoa AS STRING) AS dta_emissao_cart_trab_pessoa,
    CAST(sig_uf_cart_trab_pessoa AS STRING) AS sig_uf_cart_trab_pessoa,
    CAST(num_titulo_eleitor_pessoa AS STRING) AS num_titulo_eleitor_pessoa,
    CAST(num_zona_tit_eleitor_pessoa AS STRING) AS num_zona_tit_eleitor_pessoa,
    CAST(num_secao_tit_eleitor_pessoa AS STRING) AS num_secao_tit_eleitor_pessoa,
    CAST(cod_termo___matricula__certid_pessoa AS STRING) AS cod_termo___matricula__certid_pessoa,
    CAST(num_identidade_pessoa AS STRING) AS num_identidade_pessoa,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.05_0604_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_fam AS STRING) AS chv_natural_prefeitura_fam,
    CAST(cod_familiar_fam AS STRING) AS cod_familiar_fam,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(cod_certidao_civil_pessoa AS STRING) AS cod_certidao_civil_pessoa,
    CAST(nom_cartorio_pessoa AS STRING) AS nom_cartorio_pessoa,
    CAST(cod_livro_termo_certid_pessoa AS STRING) AS cod_livro_termo_certid_pessoa,
    CAST(cod_folha_termo_certid_pessoa AS STRING) AS cod_folha_termo_certid_pessoa,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(dta_emissao_certid_pessoa AS STRING) AS dta_emissao_certid_pessoa,
    CAST(sig_uf_certid_pessoa AS STRING) AS sig_uf_certid_pessoa,
    CAST(nom_munic_certid_pessoa AS STRING) AS nom_munic_certid_pessoa,
    CAST(cod_ibge_munic_certid_pessoa AS STRING) AS cod_ibge_munic_certid_pessoa,
    CAST(cod_cartorio_certid_pessoa AS STRING) AS cod_cartorio_certid_pessoa,
    CAST(num_cpf_pessoa AS STRING) AS num_cpf_pessoa,
    CAST(vazio_3 AS STRING) AS vazio_3,
    CAST(cod_complemento_pessoa AS STRING) AS cod_complemento_pessoa,
    CAST(dta_emissao_ident_pessoa AS STRING) AS dta_emissao_ident_pessoa,
    CAST(sig_uf_ident_pessoa AS STRING) AS sig_uf_ident_pessoa,
    CAST(sig_orgao_emissor_pessoa AS STRING) AS sig_orgao_emissor_pessoa,
    CAST(num_cart_trab_prev_soc_pessoa AS STRING) AS num_cart_trab_prev_soc_pessoa,
    CAST(num_serie_trab_prev_soc_pessoa AS STRING) AS num_serie_trab_prev_soc_pessoa,
    CAST(dta_emissao_cart_trab_pessoa AS STRING) AS dta_emissao_cart_trab_pessoa,
    CAST(sig_uf_cart_trab_pessoa AS STRING) AS sig_uf_cart_trab_pessoa,
    CAST(num_titulo_eleitor_pessoa AS STRING) AS num_titulo_eleitor_pessoa,
    CAST(num_zona_tit_eleitor_pessoa AS STRING) AS num_zona_tit_eleitor_pessoa,
    CAST(num_secao_tit_eleitor_pessoa AS STRING) AS num_secao_tit_eleitor_pessoa,
    CAST(cod_termo___matricula__certid_pessoa AS STRING) AS cod_termo___matricula__certid_pessoa,
    CAST(num_identidade_pessoa AS STRING) AS num_identidade_pessoa,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.05_0609_test`

