
SELECT
    CAST(chv_natural_prefeitura_membt AS string) AS id_prefeitura_origem,
    CAST(cod_familiar_membt AS string) AS id_familia_origem,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(dta_transferencia_membt AS date) AS data_transferencia_membro,
    CAST(cod_est_cadastral_atual_membt AS string) AS id_estado_cadastro_transferencia_membro,
    CAST(nom_memb_t AS string) AS nome,
    CAST(num_nis_membt AS string) AS nis,
    CAST(nom_apelido_membt AS string) AS apelido,
    CAST(cod_sexo_membt AS string) AS sexo,
    CAST(dta_nasc_membt AS date) AS data_nascimento,
    CAST(cod_raca_cor_membt AS string) AS id_raca_cor,
    CAST(nom_completo_mae_membt AS string) AS nome_mae,
    CAST(ind_nom_completo_mae_membt AS string) AS nao_sabe_nome_mae,
    CAST(nom_completo_pai_membt AS string) AS nome_pai,
    CAST(ind_nom_completo_pai_membt AS string) AS nao_sabe_nome_pai,
    CAST(vazio_2 AS string) AS vazio,
    CAST(sig_uf_munic_nasc_membt AS string) AS sigla_uf_nascimento,
    CAST(ind_uf_munic_nasc_membt AS string) AS sabe_sigla_uf_nascimento,
    CAST(nom_ibge_munic_nasc_membt AS string) AS municipio_nascimento,
    CAST(cod_ibge_munic_nasc_membt AS string) AS id_municipio_nascimento,
    CAST(ind_ibge_munic_nasc_membt AS string) AS sabe_municipio_nascimento,
    CAST(nom_pais_origem_membt AS string) AS pais_nascimento,
    CAST(vazio_3 AS string) AS vazio,
    CAST(ind_pais_origem_membt AS string) AS nao_sabe_pais_nascimento,
    CAST(cod_certidao_registrada_membt AS string) AS id_certidao_registrada_cartorio,
    CAST(cod_destino_prefeitura_membt AS string) AS id_prefeitura_destino_transferencia,
    CAST(cod_destino_familia_membt AS string) AS id_familia_destino_transferencia,
    CAST(cod_pais_origem_membt AS string) AS id_pais_nascimento,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.17_0601_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_membt AS string) AS id_prefeitura_origem,
    CAST(cod_familiar_membt AS string) AS id_familia_origem,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(dta_transferencia_membt AS date) AS data_transferencia_membro,
    CAST(cod_est_cadastral_atual_membt AS string) AS id_estado_cadastro_transferencia_membro,
    CAST(nom_memb_t AS string) AS nome,
    CAST(num_nis_membt AS string) AS nis,
    CAST(nom_apelido_membt AS string) AS apelido,
    CAST(cod_sexo_membt AS string) AS sexo,
    CAST(dta_nasc_membt AS date) AS data_nascimento,
    CAST(cod_raca_cor_membt AS string) AS id_raca_cor,
    CAST(nom_completo_mae_membt AS string) AS nome_mae,
    CAST(ind_nom_completo_mae_membt AS string) AS nao_sabe_nome_mae,
    CAST(nom_completo_pai_membt AS string) AS nome_pai,
    CAST(ind_nom_completo_pai_membt AS string) AS nao_sabe_nome_pai,
    CAST(vazio_2 AS string) AS vazio,
    CAST(sig_uf_munic_nasc_membt AS string) AS sigla_uf_nascimento,
    CAST(ind_uf_munic_nasc_membt AS string) AS sabe_sigla_uf_nascimento,
    CAST(nom_ibge_munic_nasc_membt AS string) AS municipio_nascimento,
    CAST(cod_ibge_munic_nasc_membt AS string) AS id_municipio_nascimento,
    CAST(ind_ibge_munic_nasc_membt AS string) AS sabe_municipio_nascimento,
    CAST(nom_pais_origem_membt AS string) AS pais_nascimento,
    CAST(vazio_3 AS string) AS vazio,
    CAST(ind_pais_origem_membt AS string) AS nao_sabe_pais_nascimento,
    CAST(cod_certidao_registrada_membt AS string) AS id_certidao_registrada_cartorio,
    CAST(cod_destino_prefeitura_membt AS string) AS id_prefeitura_destino_transferencia,
    CAST(cod_destino_familia_membt AS string) AS id_familia_destino_transferencia,
    CAST(cod_pais_origem_membt AS string) AS id_pais_nascimento,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.17_0604_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_membt AS string) AS id_prefeitura_origem,
    CAST(cod_familiar_membt AS string) AS id_familia_origem,
    CAST(num_membro_fmla AS int64) AS membros_familia,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(dta_transferencia_membt AS date) AS data_transferencia_membro,
    CAST(cod_est_cadastral_atual_membt AS string) AS id_estado_cadastro_transferencia_membro,
    CAST(nom_memb_t AS string) AS nome,
    CAST(num_nis_membt AS string) AS nis,
    CAST(nom_apelido_membt AS string) AS apelido,
    CAST(cod_sexo_membt AS string) AS sexo,
    CAST(dta_nasc_membt AS date) AS data_nascimento,
    CAST(cod_raca_cor_membt AS string) AS id_raca_cor,
    CAST(nom_completo_mae_membt AS string) AS nome_mae,
    CAST(ind_nom_completo_mae_membt AS string) AS nao_sabe_nome_mae,
    CAST(nom_completo_pai_membt AS string) AS nome_pai,
    CAST(ind_nom_completo_pai_membt AS string) AS nao_sabe_nome_pai,
    CAST(vazio_2 AS string) AS vazio,
    CAST(sig_uf_munic_nasc_membt AS string) AS sigla_uf_nascimento,
    CAST(ind_uf_munic_nasc_membt AS string) AS sabe_sigla_uf_nascimento,
    CAST(nom_ibge_munic_nasc_membt AS string) AS municipio_nascimento,
    CAST(cod_ibge_munic_nasc_membt AS string) AS id_municipio_nascimento,
    CAST(ind_ibge_munic_nasc_membt AS string) AS sabe_municipio_nascimento,
    CAST(nom_pais_origem_membt AS string) AS pais_nascimento,
    CAST(vazio_3 AS string) AS vazio,
    CAST(ind_pais_origem_membt AS string) AS nao_sabe_pais_nascimento,
    CAST(cod_certidao_registrada_membt AS string) AS id_certidao_registrada_cartorio,
    CAST(cod_destino_prefeitura_membt AS string) AS id_prefeitura_destino_transferencia,
    CAST(cod_destino_familia_membt AS string) AS id_familia_destino_transferencia,
    CAST(cod_pais_origem_membt AS string) AS id_pais_nascimento,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.17_0609_test`

