
SELECT
    CAST(chv_natural_prefeitura_membt AS STRING) AS chv_natural_prefeitura_membt,
    CAST(cod_familiar_membt AS STRING) AS cod_familiar_membt,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_transferencia_membt AS STRING) AS dta_transferencia_membt,
    CAST(cod_est_cadastral_atual_membt AS STRING) AS cod_est_cadastral_atual_membt,
    CAST(nom_memb_t AS STRING) AS nom_memb_t,
    CAST(num_nis_membt AS STRING) AS num_nis_membt,
    CAST(nom_apelido_membt AS STRING) AS nom_apelido_membt,
    CAST(cod_sexo_membt AS STRING) AS cod_sexo_membt,
    CAST(dta_nasc_membt AS STRING) AS dta_nasc_membt,
    CAST(cod_raca_cor_membt AS STRING) AS cod_raca_cor_membt,
    CAST(nom_completo_mae_membt AS STRING) AS nom_completo_mae_membt,
    CAST(ind_nom_completo_mae_membt AS STRING) AS ind_nom_completo_mae_membt,
    CAST(nom_completo_pai_membt AS STRING) AS nom_completo_pai_membt,
    CAST(ind_nom_completo_pai_membt AS STRING) AS ind_nom_completo_pai_membt,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(sig_uf_munic_nasc_membt AS STRING) AS sig_uf_munic_nasc_membt,
    CAST(ind_uf_munic_nasc_membt AS STRING) AS ind_uf_munic_nasc_membt,
    CAST(nom_ibge_munic_nasc_membt AS STRING) AS nom_ibge_munic_nasc_membt,
    CAST(cod_ibge_munic_nasc_membt AS STRING) AS cod_ibge_munic_nasc_membt,
    CAST(ind_ibge_munic_nasc_membt AS STRING) AS ind_ibge_munic_nasc_membt,
    CAST(nom_pais_origem_membt AS STRING) AS nom_pais_origem_membt,
    CAST(vazio_3 AS STRING) AS vazio_3,
    CAST(ind_pais_origem_membt AS STRING) AS ind_pais_origem_membt,
    CAST(cod_certidao_registrada_membt AS STRING) AS cod_certidao_registrada_membt,
    CAST(cod_destino_prefeitura_membt AS STRING) AS cod_destino_prefeitura_membt,
    CAST(cod_destino_familia_membt AS STRING) AS cod_destino_familia_membt,
    CAST(cod_pais_origem_membt AS STRING) AS cod_pais_origem_membt,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.17_0601_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_membt AS STRING) AS chv_natural_prefeitura_membt,
    CAST(cod_familiar_membt AS STRING) AS cod_familiar_membt,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_transferencia_membt AS STRING) AS dta_transferencia_membt,
    CAST(cod_est_cadastral_atual_membt AS STRING) AS cod_est_cadastral_atual_membt,
    CAST(nom_memb_t AS STRING) AS nom_memb_t,
    CAST(num_nis_membt AS STRING) AS num_nis_membt,
    CAST(nom_apelido_membt AS STRING) AS nom_apelido_membt,
    CAST(cod_sexo_membt AS STRING) AS cod_sexo_membt,
    CAST(dta_nasc_membt AS STRING) AS dta_nasc_membt,
    CAST(cod_raca_cor_membt AS STRING) AS cod_raca_cor_membt,
    CAST(nom_completo_mae_membt AS STRING) AS nom_completo_mae_membt,
    CAST(ind_nom_completo_mae_membt AS STRING) AS ind_nom_completo_mae_membt,
    CAST(nom_completo_pai_membt AS STRING) AS nom_completo_pai_membt,
    CAST(ind_nom_completo_pai_membt AS STRING) AS ind_nom_completo_pai_membt,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(sig_uf_munic_nasc_membt AS STRING) AS sig_uf_munic_nasc_membt,
    CAST(ind_uf_munic_nasc_membt AS STRING) AS ind_uf_munic_nasc_membt,
    CAST(nom_ibge_munic_nasc_membt AS STRING) AS nom_ibge_munic_nasc_membt,
    CAST(cod_ibge_munic_nasc_membt AS STRING) AS cod_ibge_munic_nasc_membt,
    CAST(ind_ibge_munic_nasc_membt AS STRING) AS ind_ibge_munic_nasc_membt,
    CAST(nom_pais_origem_membt AS STRING) AS nom_pais_origem_membt,
    CAST(vazio_3 AS STRING) AS vazio_3,
    CAST(ind_pais_origem_membt AS STRING) AS ind_pais_origem_membt,
    CAST(cod_certidao_registrada_membt AS STRING) AS cod_certidao_registrada_membt,
    CAST(cod_destino_prefeitura_membt AS STRING) AS cod_destino_prefeitura_membt,
    CAST(cod_destino_familia_membt AS STRING) AS cod_destino_familia_membt,
    CAST(cod_pais_origem_membt AS STRING) AS cod_pais_origem_membt,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.17_0604_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_membt AS STRING) AS chv_natural_prefeitura_membt,
    CAST(cod_familiar_membt AS STRING) AS cod_familiar_membt,
    CAST(num_membro_fmla AS STRING) AS num_membro_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_transferencia_membt AS STRING) AS dta_transferencia_membt,
    CAST(cod_est_cadastral_atual_membt AS STRING) AS cod_est_cadastral_atual_membt,
    CAST(nom_memb_t AS STRING) AS nom_memb_t,
    CAST(num_nis_membt AS STRING) AS num_nis_membt,
    CAST(nom_apelido_membt AS STRING) AS nom_apelido_membt,
    CAST(cod_sexo_membt AS STRING) AS cod_sexo_membt,
    CAST(dta_nasc_membt AS STRING) AS dta_nasc_membt,
    CAST(cod_raca_cor_membt AS STRING) AS cod_raca_cor_membt,
    CAST(nom_completo_mae_membt AS STRING) AS nom_completo_mae_membt,
    CAST(ind_nom_completo_mae_membt AS STRING) AS ind_nom_completo_mae_membt,
    CAST(nom_completo_pai_membt AS STRING) AS nom_completo_pai_membt,
    CAST(ind_nom_completo_pai_membt AS STRING) AS ind_nom_completo_pai_membt,
    CAST(vazio_2 AS STRING) AS vazio_2,
    CAST(sig_uf_munic_nasc_membt AS STRING) AS sig_uf_munic_nasc_membt,
    CAST(ind_uf_munic_nasc_membt AS STRING) AS ind_uf_munic_nasc_membt,
    CAST(nom_ibge_munic_nasc_membt AS STRING) AS nom_ibge_munic_nasc_membt,
    CAST(cod_ibge_munic_nasc_membt AS STRING) AS cod_ibge_munic_nasc_membt,
    CAST(ind_ibge_munic_nasc_membt AS STRING) AS ind_ibge_munic_nasc_membt,
    CAST(nom_pais_origem_membt AS STRING) AS nom_pais_origem_membt,
    CAST(vazio_3 AS STRING) AS vazio_3,
    CAST(ind_pais_origem_membt AS STRING) AS ind_pais_origem_membt,
    CAST(cod_certidao_registrada_membt AS STRING) AS cod_certidao_registrada_membt,
    CAST(cod_destino_prefeitura_membt AS STRING) AS cod_destino_prefeitura_membt,
    CAST(cod_destino_familia_membt AS STRING) AS cod_destino_familia_membt,
    CAST(cod_pais_origem_membt AS STRING) AS cod_pais_origem_membt,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.17_0609_test`

