
SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS chv_natural_prefeitura_rl,
    CAST(cod_familiar_rl AS STRING) AS cod_familiar_rl,
    CAST(num_rl_fmla AS STRING) AS num_rl_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_cadastramento_rl AS STRING) AS dta_cadastramento_rl,
    CAST(nom_pessoa_rl AS STRING) AS nom_pessoa_rl,
    CAST(num_nis_pessoa_rl AS STRING) AS num_nis_pessoa_rl,
    CAST(cod_sexo_rl AS STRING) AS cod_sexo_rl,
    CAST(dta_nasc_rl AS STRING) AS dta_nasc_rl,
    CAST(nom_completo_mae_rl AS STRING) AS nom_completo_mae_rl,
    CAST(ind_nom_completo_mae_rl AS STRING) AS ind_nom_completo_mae_rl,
    CAST(nom_completo_pai_rl AS STRING) AS nom_completo_pai_rl,
    CAST(ind_nom_completo_pai_rl AS STRING) AS ind_nom_completo_pai_rl,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS cod_ibge_municipio_nascimento_rl,
    CAST(nome_municipio_nascimento_rl AS STRING) AS nome_municipio_nascimento_rl,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_rl,
    CAST(cod_pais_nasicmento_rl AS STRING) AS cod_pais_nasicmento_rl,
    CAST(nome_pais_nascimento_rl AS STRING) AS nome_pais_nascimento_rl,
    CAST(num_cpf_rl AS STRING) AS num_cpf_rl,
    CAST(ic_obito_rl AS STRING) AS ic_obito_rl,
    CAST(ic_obito_acatado_rl AS STRING) AS ic_obito_acatado_rl,
    CAST(num_ddd_contato_1_rl AS STRING) AS num_ddd_contato_1_rl,
    CAST(num_tel_contato_1_rl AS STRING) AS num_tel_contato_1_rl,
    CAST(num_ddd_contato_2_rl AS STRING) AS num_ddd_contato_2_rl,
    CAST(num_tel_contato_2_rl AS STRING) AS num_tel_contato_2_rl,
    CAST(email_rl AS STRING) AS email_rl,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS desc_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS chv_natural_rl,
    CAST(nome_tipo_logradouro_rl AS STRING) AS nome_tipo_logradouro_rl,
    CAST(nome_logradouro_rl AS STRING) AS nome_logradouro_rl,
    CAST(num_logradouro_rl AS STRING) AS num_logradouro_rl,
    CAST(desc_complemento_lograd_rl AS STRING) AS desc_complemento_lograd_rl,
    CAST(num_cep_rl AS STRING) AS num_cep_rl,
    CAST(nome_bairro_rl AS STRING) AS nome_bairro_rl,
    CAST(numero_municipio_rl AS STRING) AS numero_municipio_rl,
    CAST(nome_municipio_rl AS STRING) AS nome_municipio_rl,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_rl,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.20_0601_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS chv_natural_prefeitura_rl,
    CAST(cod_familiar_rl AS STRING) AS cod_familiar_rl,
    CAST(num_rl_fmla AS STRING) AS num_rl_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_cadastramento_rl AS STRING) AS dta_cadastramento_rl,
    CAST(nom_pessoa_rl AS STRING) AS nom_pessoa_rl,
    CAST(num_nis_pessoa_rl AS STRING) AS num_nis_pessoa_rl,
    CAST(cod_sexo_rl AS STRING) AS cod_sexo_rl,
    CAST(dta_nasc_rl AS STRING) AS dta_nasc_rl,
    CAST(nom_completo_mae_rl AS STRING) AS nom_completo_mae_rl,
    CAST(ind_nom_completo_mae_rl AS STRING) AS ind_nom_completo_mae_rl,
    CAST(nom_completo_pai_rl AS STRING) AS nom_completo_pai_rl,
    CAST(ind_nom_completo_pai_rl AS STRING) AS ind_nom_completo_pai_rl,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS cod_ibge_municipio_nascimento_rl,
    CAST(nome_municipio_nascimento_rl AS STRING) AS nome_municipio_nascimento_rl,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_rl,
    CAST(cod_pais_nasicmento_rl AS STRING) AS cod_pais_nasicmento_rl,
    CAST(nome_pais_nascimento_rl AS STRING) AS nome_pais_nascimento_rl,
    CAST(num_cpf_rl AS STRING) AS num_cpf_rl,
    CAST(ic_obito_rl AS STRING) AS ic_obito_rl,
    CAST(ic_obito_acatado_rl AS STRING) AS ic_obito_acatado_rl,
    CAST(num_ddd_contato_1_rl AS STRING) AS num_ddd_contato_1_rl,
    CAST(num_tel_contato_1_rl AS STRING) AS num_tel_contato_1_rl,
    CAST(num_ddd_contato_2_rl AS STRING) AS num_ddd_contato_2_rl,
    CAST(num_tel_contato_2_rl AS STRING) AS num_tel_contato_2_rl,
    CAST(email_rl AS STRING) AS email_rl,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS desc_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS chv_natural_rl,
    CAST(nome_tipo_logradouro_rl AS STRING) AS nome_tipo_logradouro_rl,
    CAST(nome_logradouro_rl AS STRING) AS nome_logradouro_rl,
    CAST(num_logradouro_rl AS STRING) AS num_logradouro_rl,
    CAST(desc_complemento_lograd_rl AS STRING) AS desc_complemento_lograd_rl,
    CAST(num_cep_rl AS STRING) AS num_cep_rl,
    CAST(nome_bairro_rl AS STRING) AS nome_bairro_rl,
    CAST(numero_municipio_rl AS STRING) AS numero_municipio_rl,
    CAST(nome_municipio_rl AS STRING) AS nome_municipio_rl,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_rl,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.20_0604_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS STRING) AS chv_natural_prefeitura_rl,
    CAST(cod_familiar_rl AS STRING) AS cod_familiar_rl,
    CAST(num_rl_fmla AS STRING) AS num_rl_fmla,
    CAST(vazio AS STRING) AS vazio,
    CAST(num_reg_arquivo AS STRING) AS num_reg_arquivo,
    CAST(dta_cadastramento_rl AS STRING) AS dta_cadastramento_rl,
    CAST(nom_pessoa_rl AS STRING) AS nom_pessoa_rl,
    CAST(num_nis_pessoa_rl AS STRING) AS num_nis_pessoa_rl,
    CAST(cod_sexo_rl AS STRING) AS cod_sexo_rl,
    CAST(dta_nasc_rl AS STRING) AS dta_nasc_rl,
    CAST(nom_completo_mae_rl AS STRING) AS nom_completo_mae_rl,
    CAST(ind_nom_completo_mae_rl AS STRING) AS ind_nom_completo_mae_rl,
    CAST(nom_completo_pai_rl AS STRING) AS nom_completo_pai_rl,
    CAST(ind_nom_completo_pai_rl AS STRING) AS ind_nom_completo_pai_rl,
    CAST(cod_ibge_municipio_nascimento_rl AS STRING) AS cod_ibge_municipio_nascimento_rl,
    CAST(nome_municipio_nascimento_rl AS STRING) AS nome_municipio_nascimento_rl,
    CAST(sigla_uf_nascimento_rl AS STRING) AS sigla_uf_nascimento_rl,
    CAST(cod_pais_nasicmento_rl AS STRING) AS cod_pais_nasicmento_rl,
    CAST(nome_pais_nascimento_rl AS STRING) AS nome_pais_nascimento_rl,
    CAST(num_cpf_rl AS STRING) AS num_cpf_rl,
    CAST(ic_obito_rl AS STRING) AS ic_obito_rl,
    CAST(ic_obito_acatado_rl AS STRING) AS ic_obito_acatado_rl,
    CAST(num_ddd_contato_1_rl AS STRING) AS num_ddd_contato_1_rl,
    CAST(num_tel_contato_1_rl AS STRING) AS num_tel_contato_1_rl,
    CAST(num_ddd_contato_2_rl AS STRING) AS num_ddd_contato_2_rl,
    CAST(num_tel_contato_2_rl AS STRING) AS num_tel_contato_2_rl,
    CAST(email_rl AS STRING) AS email_rl,
    CAST(tipo_representacao_legal AS STRING) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS STRING) AS desc_representacao_legal,
    CAST(chv_natural_rl AS STRING) AS chv_natural_rl,
    CAST(nome_tipo_logradouro_rl AS STRING) AS nome_tipo_logradouro_rl,
    CAST(nome_logradouro_rl AS STRING) AS nome_logradouro_rl,
    CAST(num_logradouro_rl AS STRING) AS num_logradouro_rl,
    CAST(desc_complemento_lograd_rl AS STRING) AS desc_complemento_lograd_rl,
    CAST(num_cep_rl AS STRING) AS num_cep_rl,
    CAST(nome_bairro_rl AS STRING) AS nome_bairro_rl,
    CAST(numero_municipio_rl AS STRING) AS numero_municipio_rl,
    CAST(nome_municipio_rl AS STRING) AS nome_municipio_rl,
    CAST(sigla_uf_rl AS STRING) AS sigla_uf_rl,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.20_0609_test`

