
SELECT
    CAST(chv_natural_prefeitura_rl AS string) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS string) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS string) AS id_interno_representante_legal,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(dta_cadastramento_rl AS date) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS string) AS representante_legal,
    CAST(num_nis_pessoa_rl AS string) AS nis_representante_legal,
    CAST(cod_sexo_rl AS string) AS id_sexo_representante_legal,
    CAST(dta_nasc_rl AS date) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS string) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS string) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS string) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS string) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS string) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS string) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS string) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS string) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS string) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS string) AS cpf_representante_legal,
    CAST(ic_obito_rl AS string) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS string) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS string) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS string) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS string) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS string) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS string) AS email_representante_legal,
    CAST(tipo_representacao_legal AS string) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS string) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS string) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS string) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS string) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS string) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS string) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS string) AS cep_representante_legal,
    CAST(nome_bairro_rl AS string) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS string) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS string) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS string) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.20_0601_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS string) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS string) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS string) AS id_interno_representante_legal,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(dta_cadastramento_rl AS date) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS string) AS representante_legal,
    CAST(num_nis_pessoa_rl AS string) AS nis_representante_legal,
    CAST(cod_sexo_rl AS string) AS id_sexo_representante_legal,
    CAST(dta_nasc_rl AS date) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS string) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS string) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS string) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS string) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS string) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS string) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS string) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS string) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS string) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS string) AS cpf_representante_legal,
    CAST(ic_obito_rl AS string) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS string) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS string) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS string) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS string) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS string) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS string) AS email_representante_legal,
    CAST(tipo_representacao_legal AS string) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS string) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS string) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS string) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS string) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS string) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS string) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS string) AS cep_representante_legal,
    CAST(nome_bairro_rl AS string) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS string) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS string) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS string) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.20_0604_test`

UNION ALL


SELECT
    CAST(chv_natural_prefeitura_rl AS string) AS id_prefeitura_representante_legal,
    CAST(cod_familiar_rl AS string) AS id_familia_representante_legal,
    CAST(num_rl_fmla AS string) AS id_interno_representante_legal,
    CAST(vazio AS string) AS vazio,
    CAST(num_reg_arquivo AS string) AS numero_registro_arquivo,
    CAST(dta_cadastramento_rl AS date) AS data_cadastro_representante_legal,
    CAST(nom_pessoa_rl AS string) AS representante_legal,
    CAST(num_nis_pessoa_rl AS string) AS nis_representante_legal,
    CAST(cod_sexo_rl AS string) AS id_sexo_representante_legal,
    CAST(dta_nasc_rl AS date) AS data_nascimento_representante_legal,
    CAST(nom_completo_mae_rl AS string) AS mae_representante_legal,
    CAST(ind_nom_completo_mae_rl AS string) AS nao_sabe_nome_mae_representante_legal,
    CAST(nom_completo_pai_rl AS string) AS pai_representante_legal,
    CAST(ind_nom_completo_pai_rl AS string) AS nao_sabe_nome_pai_representante_legal,
    CAST(cod_ibge_municipio_nascimento_rl AS string) AS id_minicipio_nascimento_representante_legal,
    CAST(nome_municipio_nascimento_rl AS string) AS municipio_nascimento_representante_legal,
    CAST(sigla_uf_nascimento_rl AS string) AS sigla_uf_nascimento_representante_legal,
    CAST(cod_pais_nasicmento_rl AS string) AS id_pais_nascimento_representante_legal,
    CAST(nome_pais_nascimento_rl AS string) AS pais_nascimento_representante_legal,
    CAST(num_cpf_rl AS string) AS cpf_representante_legal,
    CAST(ic_obito_rl AS string) AS obito_representante_legal,
    CAST(ic_obito_acatado_rl AS string) AS obito_acatado_representante_legal,
    CAST(num_ddd_contato_1_rl AS string) AS contato_ddd_representante_legal,
    CAST(num_tel_contato_1_rl AS string) AS contato_telefone_representante_legal,
    CAST(num_ddd_contato_2_rl AS string) AS contato_ddd_2_representante_legal,
    CAST(num_tel_contato_2_rl AS string) AS contato_telefone_2_representante_legal,
    CAST(email_rl AS string) AS email_representante_legal,
    CAST(tipo_representacao_legal AS string) AS tipo_representacao_legal,
    CAST(desc_representacao_legal AS string) AS descricao_representacao_legal,
    CAST(chv_natural_rl AS string) AS id_representante_legal,
    CAST(nome_tipo_logradouro_rl AS string) AS tipo_logradouro_representante_legal,
    CAST(nome_logradouro_rl AS string) AS logradouro_representante_legal,
    CAST(num_logradouro_rl AS string) AS numero_logradouro_representante_legal,
    CAST(desc_complemento_lograd_rl AS string) AS descricao_complemento_logradouro_representante_legal,
    CAST(num_cep_rl AS string) AS cep_representante_legal,
    CAST(nome_bairro_rl AS string) AS bairro_representante_legal,
    CAST(numero_municipio_rl AS string) AS id_municipio_representante_legal,
    CAST(nome_municipio_rl AS string) AS municipio_representante_legal,
    CAST(sigla_uf_rl AS string) AS sigla_uf_representante_legal,
    SAFE_CAST(versao_layout_particao AS STRING) AS versao_layout_particao,
    SAFE_CAST(data_particao AS DATE) AS data_particao
FROM `rj-smas.protecao_social_cadunico_test_versao.20_0609_test`

